# Project 2A: Ames Housing Data & Kaggle Challenge

## Problem Statement

Due to the increasing population in Ames Iowa, there is an increasing demand for housing for the residents in Ames Iowa. As it is the same in many place, the sales price of a house typically will vary according to its types and features. As a data scientist working in a private construction company in Ames Iowa, we are interested to first explore the association between residential features and its sales prices. This will allows us to gain an insight to optimize the construction plan to include those features that are correlated to prices, which will translate to higher sales profits.

### Overall Contents:
- [Background](#1.-Background) **(In this notebook)**
- [Data Cleaning](#2.-Data-Cleaning) **(In this notebook)**
- Exploratory Data Analysis
- Modeling
- Conclusions and Recommendations

## 1. Background

Houses styles in United states varies across different parts of the states depending on the location you are in. In 1991, many of the houses in United States are landed property with 60% of the USA land is a private land,[[1]](https://www.summitpost.org/public-and-private-land-percentages-by-us-states/186111) thus making the construction a lucrative business. As the human population are increasing,this increases the demand of the need of new houses to be build and existing houses to be remodeled making the knowledge of consumer desirables features an important asset.

The need of new houses also extend to Ames, Iowa, which is a city in Story County,Iowa,[[2]](https://www.niche.com/places-to-live/ames-story-ia/) which is located in the midwest region of the United States. The housing unit with owner-occupied in 2019 is 40.7% with a median value of these housing units of USD205,900.[[3]](https://www.census.gov/quickfacts/amescityiowa) With the home appreaction in Ames increases quickly up to 28.1% in the last 10 years [[4]](https://www.bestplaces.net/housing/city/iowa/ames), Awes, Iowa faced a challenge of purchasing an affordable housing resulting in an increase in remodeling run down house leading to the disinterest of developers in Ames city[[5]](https://www.thegazette.com/regional-development/iowas-affordable-housing-struggle/). With the need of more housing, our private construction company in Ames, Iowa would like to gain further insight to explore the association between residential that are correlated to prices. This allows the company to integrate this domain knowledge of consumer desirables features to build more affordable housing, thus translating to higher sales profits. Hence, as a data scientist in this company, I will be handling on this project and our goals are the following:

1. To identify the features that are highly correlated to sale prices (from both domain knowledge and technical analysis)

2. To build a good model to estimate and predict the sales price of housing in Ames Iowa

By knowing what are the key features that affect the sales price, our construction company will be able to use this insight to make informed business decisions, such as to build desirable affordable houses that are highly marketable and advise potential house owners to renovate their house to include features that are likely to increase sales price prior selling.


### 1.1 Datasets

The dataset used for this analysis are as followed:-

* [`train`]: Ames Housing Train Data - labeled as housing_data
* [`test `]: Ames Housing Test Data - labeled as test_housing_data

Data source: [Ames Housing Data](https://www.kaggle.com/c/dsi-us-11-project-2-regression-challenge/data) obtained from database [Ames Iowa Assessor's Office](http://www.cityofames.org/assessor/)


The dataset contains the individual residential properties features that were sold in Ames, Iowa between 2006 to 2010. The data consists of 2051 observations with 81 features in which 14 discrete, 20 continous, 22 nominal and 23 ordinal. The main features are as followed:-

1. Parcel identification number (PID)
2. Type and style of dwelling
3. Type of zoning
4. Land lot (frontage, area, road or alley access, shape, flatness, configuration, slope)
5. Physical locations (neighbourhood and amenities proximity )
6. Overall house condition and quality
7. Construction & remodel date
8. Presence of utilities
9. Housing structure
  * Roof style, materials
  * Exterior materials, quality and condition
  * Masonry veneer type and area
  * Type of foundation
10. House layout
  * Area (square feet) (first/second Floor, low quality of finished floors, above grade (ground) living area)
  * Basement (quality, condition, exposure, finished/unfinished/total area, full/half Bathrooms)
  * Heating (type, quality and condition)
  * Central air-conditioning
  * Electrical system
  * Above grade (ground) utilities
      * Full/half bathrooms
      * Bedrooms
      * Kitchen (number and its quality)
      * Total rooms (does not include bathrooms)
      * Fireplaces (number and its quality)
  * Home functionality
  * Garage (location, year built, interior finish, total area, car capacity area, quality, condition)
  * Exterior
      * Paved driveway
      * Wood deck area
      * Porch area (square feet) (open, enclosed, three season, screen)
      * Pool (area, quality)
      * Fence quality
      * Miscellaneous features
11. House value
  * Value of miscellneous feature
  * Month, year sold
  * Type of sale
  * Sale price ($$)

## 2. Data Cleaning

### 2.1 Libraries Import

In [6]:
# Imports:
import pandas as pd
import numpy as np

### 2.2 Data Import

In [7]:
# Import of Ames Housing Train Data from csv
housing_data = pd.read_csv('../datasets/train.csv')
test_housing_data = pd.read_csv('../datasets/test.csv')

### 2.3 Data Cleaning

### 2.3.1 Overview

In [8]:
# Header of housing_data
housing_data.head()

Id        PID  MS SubClass MS Zoning  Lot Frontage  Lot Area Street Alley  \
0  109  533352170           60        RL           NaN     13517   Pave   NaN   
1  544  531379050           60        RL          43.0     11492   Pave   NaN   
2  153  535304180           20        RL          68.0      7922   Pave   NaN   
3  318  916386060           60        RL          73.0      9802   Pave   NaN   
4  255  906425045           50        RL          82.0     14235   Pave   NaN   

  Lot Shape Land Contour  ... Screen Porch Pool Area Pool QC Fence  \
0       IR1          Lvl  ...            0         0     NaN   NaN   
1       IR1          Lvl  ...            0         0     NaN   NaN   
2       Reg          Lvl  ...            0         0     NaN   NaN   
3       Reg          Lvl  ...            0         0     NaN   NaN   
4       IR1          Lvl  ...            0         0     NaN   NaN   

  Misc Feature Misc Val Mo Sold Yr Sold  Sale Type  SalePrice  
0          NaN        0       3    2010        WD      130500  
1          NaN        0       4    2009        WD      220000  
2          NaN        0       1    2010        WD      109000  
3          NaN        0       4    2010        WD      174000  
4          NaN        0       3    2010        WD      138500  

[5 rows x 81 columns]

In [9]:
# Header of housing_data
test_housing_data.head()

Id        PID  MS SubClass MS Zoning  Lot Frontage  Lot Area Street  \
0  2658  902301120          190        RM          69.0      9142   Pave   
1  2718  905108090           90        RL           NaN      9662   Pave   
2  2414  528218130           60        RL          58.0     17104   Pave   
3  1989  902207150           30        RM          60.0      8520   Pave   
4   625  535105100           20        RL           NaN      9500   Pave   

  Alley Lot Shape Land Contour  ... 3Ssn Porch Screen Porch Pool Area Pool QC  \
0  Grvl       Reg          Lvl  ...          0            0         0     NaN   
1   NaN       IR1          Lvl  ...          0            0         0     NaN   
2   NaN       IR1          Lvl  ...          0            0         0     NaN   
3   NaN       Reg          Lvl  ...          0            0         0     NaN   
4   NaN       IR1          Lvl  ...          0          185         0     NaN   

  Fence Misc Feature Misc Val Mo Sold  Yr Sold  Sale Type  
0   NaN          NaN        0       4     2006        WD   
1   NaN          NaN        0       8     2006        WD   
2   NaN          NaN        0       9     2006        New  
3   NaN          NaN        0       7     2007        WD   
4   NaN          NaN        0       7     2009        WD   

[5 rows x 80 columns]

In [10]:
# To observe the dtype and missing values
housing_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2051 entries, 0 to 2050
Data columns (total 81 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Id               2051 non-null   int64  
 1   PID              2051 non-null   int64  
 2   MS SubClass      2051 non-null   int64  
 3   MS Zoning        2051 non-null   object 
 4   Lot Frontage     1721 non-null   float64
 5   Lot Area         2051 non-null   int64  
 6   Street           2051 non-null   object 
 7   Alley            140 non-null    object 
 8   Lot Shape        2051 non-null   object 
 9   Land Contour     2051 non-null   object 
 10  Utilities        2051 non-null   object 
 11  Lot Config       2051 non-null   object 
 12  Land Slope       2051 non-null   object 
 13  Neighborhood     2051 non-null   object 
 14  Condition 1      2051 non-null   object 
 15  Condition 2      2051 non-null   object 
 16  Bldg Type        2051 non-null   object 
 17  House Style   

In [11]:
# To observe the dtype and missing values
test_housing_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 878 entries, 0 to 877
Data columns (total 80 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Id               878 non-null    int64  
 1   PID              878 non-null    int64  
 2   MS SubClass      878 non-null    int64  
 3   MS Zoning        878 non-null    object 
 4   Lot Frontage     718 non-null    float64
 5   Lot Area         878 non-null    int64  
 6   Street           878 non-null    object 
 7   Alley            58 non-null     object 
 8   Lot Shape        878 non-null    object 
 9   Land Contour     878 non-null    object 
 10  Utilities        878 non-null    object 
 11  Lot Config       878 non-null    object 
 12  Land Slope       878 non-null    object 
 13  Neighborhood     878 non-null    object 
 14  Condition 1      878 non-null    object 
 15  Condition 2      878 non-null    object 
 16  Bldg Type        878 non-null    object 
 17  House Style     

**Analysis: There are 2051 observations with 81 columns for housing_data and 878 observations with 80 columns for test_housing_data**

In housing_data, there are 2051 observations with 81 columns consisting of 42 objects, 28 integers and 11 floats.
In test_housing_data, there are 878 observations with 80 columns consisting of 42 objects, 35 integers and 3 floats.
In housing_data, there is an additional column of saleprice that is not present in the test_housing_data.
There are missing values in multiple columns in both housing_data and test_housing_data.

### 2.3.2 Renaming and drop the columns

**Analysis: Rename the columns name for coherent naming and easier navigation**

For coherent naming and easier navigation, the columns will be renamed to lower case and replace any spaces betwen the words with ("_"). In addition, the column year_remod/add and columns name starting with numeric will be changed to remove additional characters and numeric starting names in the column name.

In [12]:
# Define function to rename the column to lower case and replace the space into ("_")
def rename_replace_column (data_base):
    data_base.columns = [col.lower() for col in data_base.columns]
    data_base.columns = data_base.columns.str.replace(' ', "_")
    return data_base.head()

In [13]:
# Rename the columns for housing_data
rename_replace_column(housing_data)

id        pid  ms_subclass ms_zoning  lot_frontage  lot_area street alley  \
0  109  533352170           60        RL           NaN     13517   Pave   NaN   
1  544  531379050           60        RL          43.0     11492   Pave   NaN   
2  153  535304180           20        RL          68.0      7922   Pave   NaN   
3  318  916386060           60        RL          73.0      9802   Pave   NaN   
4  255  906425045           50        RL          82.0     14235   Pave   NaN   

  lot_shape land_contour  ... screen_porch pool_area pool_qc fence  \
0       IR1          Lvl  ...            0         0     NaN   NaN   
1       IR1          Lvl  ...            0         0     NaN   NaN   
2       Reg          Lvl  ...            0         0     NaN   NaN   
3       Reg          Lvl  ...            0         0     NaN   NaN   
4       IR1          Lvl  ...            0         0     NaN   NaN   

  misc_feature misc_val mo_sold yr_sold  sale_type  saleprice  
0          NaN        0       3    2010        WD      130500  
1          NaN        0       4    2009        WD      220000  
2          NaN        0       1    2010        WD      109000  
3          NaN        0       4    2010        WD      174000  
4          NaN        0       3    2010        WD      138500  

[5 rows x 81 columns]

In [14]:
# Rename the columns for test_housing_data
rename_replace_column(test_housing_data)

id        pid  ms_subclass ms_zoning  lot_frontage  lot_area street  \
0  2658  902301120          190        RM          69.0      9142   Pave   
1  2718  905108090           90        RL           NaN      9662   Pave   
2  2414  528218130           60        RL          58.0     17104   Pave   
3  1989  902207150           30        RM          60.0      8520   Pave   
4   625  535105100           20        RL           NaN      9500   Pave   

  alley lot_shape land_contour  ... 3ssn_porch screen_porch pool_area pool_qc  \
0  Grvl       Reg          Lvl  ...          0            0         0     NaN   
1   NaN       IR1          Lvl  ...          0            0         0     NaN   
2   NaN       IR1          Lvl  ...          0            0         0     NaN   
3   NaN       Reg          Lvl  ...          0            0         0     NaN   
4   NaN       IR1          Lvl  ...          0          185         0     NaN   

  fence misc_feature misc_val mo_sold  yr_sold  sale_type  
0   NaN          NaN        0       4     2006        WD   
1   NaN          NaN        0       8     2006        WD   
2   NaN          NaN        0       9     2006        New  
3   NaN          NaN        0       7     2007        WD   
4   NaN          NaN        0       7     2009        WD   

[5 rows x 80 columns]

In [15]:
# Rename the specific columns for housing_data to specific names
housing_data = housing_data.rename(columns = {"year_remod/add" : "year_remod", "1st_flr_sf" : "first_flr_sf", "2nd_flr_sf" : "second_fld_sf", "3ssn_porch" : "threessn_porch"})
housing_data.loc[:, ["year_remod","first_flr_sf","second_fld_sf", "threessn_porch"]].head()

year_remod  first_flr_sf  second_fld_sf  threessn_porch
0        2005           725            754               0
1        1997           913           1209               0
2        2007          1057              0               0
3        2007           744            700               0
4        1993           831            614               0

In [16]:
# Rename the specific columns for test_housing_data to specific names
test_housing_data = test_housing_data.rename(columns = {"year_remod/add" : "year_remod", "1st_flr_sf" : "first_flr_sf", "2nd_flr_sf" : "second_fld_sf", "3ssn_porch" : "threessn_porch"})
test_housing_data.loc[:, ["year_remod","first_flr_sf","second_fld_sf", "threessn_porch"]].head()

year_remod  first_flr_sf  second_fld_sf  threessn_porch
0        1950           908           1020               0
1        1977          1967              0               0
2        2006           664            832               0
3        2006           968              0               0
4        1963          1394              0               0

In [17]:
# Drop the pid column
housing_data = housing_data.drop(columns = ["id","pid"])

In [18]:
# Drop the pid column
test_housing_data = test_housing_data.drop(columns = ["id","pid"])

**Analysis: Successfully renamed the columns name for coherent naming and easier navigation**

### 2.3.3 Rename values

**Analysis: Rename the ms_zoning value names for coherent naming and easier navigation**

For coherent naming and easier navigation, the ms_zoning values will be renamed to remove additional words such as "(all)" and "(agr)".

In [19]:
housing_data.ms_zoning.unique()

array(['RL', 'RM', 'FV', 'C (all)', 'A (agr)', 'RH', 'I (all)'],
      dtype=object)

In [20]:
test_housing_data.ms_zoning.unique()

array(['RM', 'RL', 'FV', 'RH', 'C (all)', 'I (all)'], dtype=object)

In [21]:
# For housing_data and test_housing_data - Rename the ms_zoning values to remove the (all and agr)
housing_data.ms_zoning = housing_data.ms_zoning.apply(lambda string:string.replace(" (all)",""))
housing_data.ms_zoning = housing_data.ms_zoning.apply(lambda string:string.replace(" (agr)",""))

In [22]:
# For test_housing_data - Rename the ms_zoning values to remove the (all)
test_housing_data.ms_zoning = test_housing_data.ms_zoning.apply(lambda string:string.replace(" (all)",""))

In [23]:
housing_data.ms_zoning.unique()

array(['RL', 'RM', 'FV', 'C', 'A', 'RH', 'I'], dtype=object)

In [24]:
test_housing_data.ms_zoning.unique()

array(['RM', 'RL', 'FV', 'RH', 'C', 'I'], dtype=object)

**Analysis: Successfully renamed the value names for coherent naming and easier navigation**

### 2.3.4 Missing Values

In [25]:
# List of missing values for housing_data
pd.set_option('display.max_rows', 160)
housing_data.isnull().sum().sort_values(ascending=False)[0:30]

pool_qc           2042
misc_feature      1986
alley             1911
fence             1651
fireplace_qu      1000
lot_frontage       330
garage_qual        114
garage_cond        114
garage_yr_blt      114
garage_finish      114
garage_type        113
bsmt_exposure       58
bsmtfin_type_2      56
bsmt_qual           55
bsmtfin_type_1      55
bsmt_cond           55
mas_vnr_type        22
mas_vnr_area        22
bsmt_half_bath       2
bsmt_full_bath       2
bsmt_unf_sf          1
total_bsmt_sf        1
bsmtfin_sf_1         1
bsmtfin_sf_2         1
garage_cars          1
garage_area          1
exterior_2nd         0
exterior_1st         0
roof_matl            0
roof_style           0
dtype: int64

**Analysis: There are 26 columns with missing values with the main features frontage, alley, masonry, basement, fireplace, garage, pool, fence and miscellaneous features.**

The columns having missing values are pool_qc, misc_feature, alley, fence, fireplace_qu, lot_frontage, garage_finish, garage_cond, garage_qual, garage_yr_blt, garage_type, bsmt_exposure, bsmtfin_type_2, bsmtfin_type_1, bsmt_cond, bsmt_qual, mas_vnr_type, mas_vnr_area, bsmt_half_bath, bsmt_full_bath, garage_cars, garage_area, bsmt_unf_sf, bsmtfin_sf_2, total_bsmt_sf and bsmtfin_sf_1.

In [26]:
# List of missing values for test_housing_data
pd.set_option('display.max_rows', 160)
test_housing_data.isnull().sum().sort_values(ascending=False)[0:30]

pool_qc           874
misc_feature      837
alley             820
fence             706
fireplace_qu      422
lot_frontage      160
garage_cond        45
garage_qual        45
garage_yr_blt      45
garage_finish      45
garage_type        44
bsmtfin_type_1     25
bsmtfin_type_2     25
bsmt_qual          25
bsmt_cond          25
bsmt_exposure      25
electrical          1
mas_vnr_area        1
mas_vnr_type        1
year_built          0
exter_qual          0
exter_cond          0
foundation          0
exterior_2nd        0
exterior_1st        0
roof_matl           0
roof_style          0
year_remod          0
sale_type           0
overall_cond        0
dtype: int64

**Analysis: There are 19 columns with missing values with the main features frontage, alley, masonry, basement, fireplace, garage, pool, fence, electrical and miscellaneous features.**

The columns having missing values are pool_qc, misc_feature, alley, fence, fireplace_qu, lot_frontage, garage_cond, garage_qual, garage_yr_blt, garage_finish, garage_type, bsmt_exposure, bsmtfin_type_1, bsmt_qual, bsmtfin_type_2, bsmt_cond, mas_vnr_area, mas_vnr_type and electrical.

**Summary:** 
1. The common column having missing values in both housing_data and test_housing_data are the alley, basement, fence, fireplace, frontage, garage, masonry, pool and miscellaneous features.
2. test_housing_data has an additional column of missing values in elecrical.

### 2.3.4.1 Alley missing values

**1. housing_data**

In [27]:
# missing values of alley
housing_data.alley.isnull().sum()

1911

In [28]:
# The unique values in alley
housing_data.alley.unique()

array([nan, 'Pave', 'Grvl'], dtype=object)

**Analysis: The missing value of 'NA' option might suggests the missing values are no alley access."**

There are three options for the category alley, which is 'Grvl' for Gravel, 'Pave' for Paved, and 'NA' for No alley access. Thus, the missing value will be place as 'ANA' and will perform a dummy encoding to the values.

In [29]:
# Fill the missing values with 'ANA' and perform a dummy encoding to the values.
housing_data["alley"] = housing_data["alley"].fillna('ANA')
housing_data = pd.get_dummies(columns = ["alley"], drop_first = True, data = housing_data)
housing_data.head()

ms_subclass ms_zoning  lot_frontage  lot_area street lot_shape  \
0           60        RL           NaN     13517   Pave       IR1   
1           60        RL          43.0     11492   Pave       IR1   
2           20        RL          68.0      7922   Pave       Reg   
3           60        RL          73.0      9802   Pave       Reg   
4           50        RL          82.0     14235   Pave       IR1   

  land_contour utilities lot_config land_slope  ... pool_qc fence  \
0          Lvl    AllPub    CulDSac        Gtl  ...     NaN   NaN   
1          Lvl    AllPub    CulDSac        Gtl  ...     NaN   NaN   
2          Lvl    AllPub     Inside        Gtl  ...     NaN   NaN   
3          Lvl    AllPub     Inside        Gtl  ...     NaN   NaN   
4          Lvl    AllPub     Inside        Gtl  ...     NaN   NaN   

  misc_feature misc_val mo_sold  yr_sold  sale_type  saleprice  alley_Grvl  \
0          NaN        0       3     2010        WD      130500           0   
1          NaN        0       4     2009        WD      220000           0   
2          NaN        0       1     2010        WD      109000           0   
3          NaN        0       4     2010        WD      174000           0   
4          NaN        0       3     2010        WD      138500           0   

  alley_Pave  
0          0  
1          0  
2          0  
3          0  
4          0  

[5 rows x 80 columns]

**2. test_housing_data**

In [30]:
# missing values of alley
test_housing_data.alley.isnull().sum()

820

In [31]:
# The unique values in alley
test_housing_data.alley.unique()

array(['Grvl', nan, 'Pave'], dtype=object)

**Analysis: Similar to housing_data, the missing value of 'NA' option might suggests the missing values are no alley access."**

Similarly, the 'NA' for No alley access is missing out of the three options, which might suggests it to be no alley access. Thus, the missing value will be place as 'ANA' and will perform a dummy encoding to the values.

In [32]:
# Fill the missing values with 'NA' and perform a dummy encoding to the values.
test_housing_data["alley"] = test_housing_data["alley"].fillna('ANA')
test_housing_data = pd.get_dummies(columns = ["alley"], drop_first = True, data = test_housing_data)
test_housing_data.head()

ms_subclass ms_zoning  lot_frontage  lot_area street lot_shape  \
0          190        RM          69.0      9142   Pave       Reg   
1           90        RL           NaN      9662   Pave       IR1   
2           60        RL          58.0     17104   Pave       IR1   
3           30        RM          60.0      8520   Pave       Reg   
4           20        RL           NaN      9500   Pave       IR1   

  land_contour utilities lot_config land_slope  ... pool_area pool_qc fence  \
0          Lvl    AllPub     Inside        Gtl  ...         0     NaN   NaN   
1          Lvl    AllPub     Inside        Gtl  ...         0     NaN   NaN   
2          Lvl    AllPub     Inside        Gtl  ...         0     NaN   NaN   
3          Lvl    AllPub     Inside        Gtl  ...         0     NaN   NaN   
4          Lvl    AllPub     Inside        Gtl  ...         0     NaN   NaN   

  misc_feature misc_val  mo_sold  yr_sold  sale_type  alley_Grvl alley_Pave  
0          NaN        0        4     2006        WD            1          0  
1          NaN        0        8     2006        WD            0          0  
2          NaN        0        9     2006        New           0          0  
3          NaN        0        7     2007        WD            0          0  
4          NaN        0        7     2009        WD            0          0  

[5 rows x 79 columns]

**Summary: Both housing_data and test_housing_data for alley missing values has been change to 'ANA' and perform a dummy encoding to the values.**

### 2.3.4.2 Basement missing values

**1. housing_data**

In [33]:
# Checking the null for columns related to basement
housing_data.loc[(housing_data["bsmt_qual"].isnull())|
                 (housing_data["bsmt_cond"].isnull())|
                 (housing_data["bsmt_exposure"].isnull())|
                 (housing_data["bsmtfin_type_1"].isnull())|
                 (housing_data["bsmtfin_type_2"].isnull())|
                 (housing_data["bsmt_full_bath"].isnull())|
                 (housing_data["bsmt_half_bath"].isnull())|
                 (housing_data["bsmtfin_sf_1"].isnull())|
                 (housing_data["bsmtfin_sf_2"].isnull())|
                 (housing_data["bsmt_unf_sf"].isnull())|
                 (housing_data["total_bsmt_sf"].isnull()), 
                 ["bsmt_qual","bsmt_cond","bsmt_exposure",
                  "bsmtfin_type_1","bsmtfin_sf_1","bsmtfin_type_2", 
                  "bsmtfin_sf_2", "bsmt_unf_sf", "total_bsmt_sf", 
                  "bsmt_full_bath", "bsmt_half_bath"]].head()

bsmt_qual bsmt_cond bsmt_exposure bsmtfin_type_1  bsmtfin_sf_1  \
12        NaN       NaN           NaN            NaN           0.0   
93        NaN       NaN           NaN            NaN           0.0   
114       NaN       NaN           NaN            NaN           0.0   
146       NaN       NaN           NaN            NaN           0.0   
183       NaN       NaN           NaN            NaN           0.0   

    bsmtfin_type_2  bsmtfin_sf_2  bsmt_unf_sf  total_bsmt_sf  bsmt_full_bath  \
12             NaN           0.0          0.0            0.0             0.0   
93             NaN           0.0          0.0            0.0             0.0   
114            NaN           0.0          0.0            0.0             0.0   
146            NaN           0.0          0.0            0.0             0.0   
183            NaN           0.0          0.0            0.0             0.0   

     bsmt_half_bath  
12              0.0  
93              0.0  
114             0.0  
146             0.0  
183             0.0

**Analysis: Majority of the basement features have missing values when total basement area (total_bsmt_sf) is zero.**

1. When total_bsmt_sf (basement area) is 0, this suggests that there should be no other basement features.

2. For  bsmt_qual, bsmt_cond, bsmt_exposure, bsmtfin_type_1, bsmtfin_type_2, the missing values will be inputed as 'NA' for No basement when the total_bsmt_sf is 0. 

3. For full_bath and half_bath (index 616), the missing values will be inputed as 0 as the total_bsmt_sf is 0. 

4. Index 1327 has no basement information for all basement features. As all values are missing, this might suggests that there is no basement for this property. Thus, the missing values will be inputed as 'NA' and 0 for the respective columns.

In [34]:
# Change the index 1327 missing values for total_bsmt_sf, bsmtfin_sf_1 and bsmtfin_sf_2 to 0
housing_data.loc[[1327],'total_bsmt_sf'] = housing_data.loc[[1327],'total_bsmt_sf'].fillna(0)
housing_data.loc[[1327],'bsmt_unf_sf'] = housing_data.loc[[1327],'bsmt_unf_sf'].fillna(0)
housing_data.loc[[1327],'bsmtfin_sf_1'] = housing_data.loc[[1327],'bsmtfin_sf_1'].fillna(0)
housing_data.loc[[1327],'bsmtfin_sf_2'] = housing_data.loc[[1327],'bsmtfin_sf_2'].fillna(0)
housing_data.loc[[1327], ['total_bsmt_sf', "bsmt_unf_sf", 'bsmtfin_sf_1', 'bsmtfin_sf_2']].head()

total_bsmt_sf  bsmt_unf_sf  bsmtfin_sf_1  bsmtfin_sf_2
1327            0.0          0.0           0.0           0.0

In [35]:
def modify_with_criteria_onenull_onezero(data_base, modify_column, base_column, new_char):
    mask = (data_base[modify_column].isnull()) & (data_base[base_column] == 0)
    data_base.loc[mask,modify_column] = data_base.loc[mask,modify_column].fillna(new_char)
    return f"The missing values has successfully changed."

In [36]:
"""Change the missing values in bsmt_qual, bsmt_cond, bsmt_exposure, bsmtfin_type_1, bsmtfin_type_2 column to 
'NA' while for bsmt_full_bath and bsmt_half_bath columns to 0 when total_bsmt_sf is 0"""
modify_with_criteria_onenull_onezero(housing_data, "bsmt_qual", "total_bsmt_sf", 'NA')
modify_with_criteria_onenull_onezero(housing_data, "bsmt_cond", "total_bsmt_sf", 'NA')
modify_with_criteria_onenull_onezero(housing_data, "bsmt_exposure", "total_bsmt_sf", 'NA')
modify_with_criteria_onenull_onezero(housing_data, "bsmtfin_type_1", "total_bsmt_sf", 'NA')
modify_with_criteria_onenull_onezero(housing_data, "bsmtfin_type_2", "total_bsmt_sf", 'NA')
modify_with_criteria_onenull_onezero(housing_data, "bsmt_full_bath", "total_bsmt_sf", 0)
modify_with_criteria_onenull_onezero(housing_data, "bsmt_half_bath", "total_bsmt_sf", 0)

'The missing values has successfully changed.'

In [37]:
# Check for missing values in basement related columns
housing_data.loc[(housing_data["bsmt_qual"].isnull())|
                 (housing_data["bsmt_cond"].isnull())|
                 (housing_data["bsmt_exposure"].isnull())|
                 (housing_data["bsmtfin_type_1"].isnull())|
                 (housing_data["bsmtfin_type_2"].isnull())|
                 (housing_data["bsmt_full_bath"].isnull())|
                 (housing_data["bsmt_half_bath"].isnull())|
                 (housing_data["bsmtfin_sf_1"].isnull())|
                 (housing_data["bsmtfin_sf_2"].isnull())|
                 (housing_data["bsmt_unf_sf"].isnull())|
                 (housing_data["total_bsmt_sf"].isnull()), 
                 ["bsmt_qual","bsmt_cond","bsmt_exposure",
                  "bsmtfin_type_1","bsmtfin_sf_1","bsmtfin_type_2", 
                  "bsmtfin_sf_2", "bsmt_unf_sf", "total_bsmt_sf", 
                  "bsmt_full_bath", "bsmt_half_bath"]].head()

bsmt_qual bsmt_cond bsmt_exposure bsmtfin_type_1  bsmtfin_sf_1  \
1147        Gd        TA            No            GLQ        1124.0   
1456        Gd        TA           NaN            Unf           0.0   
1547        Gd        TA           NaN            Unf           0.0   
1997        Gd        TA           NaN            Unf           0.0   

     bsmtfin_type_2  bsmtfin_sf_2  bsmt_unf_sf  total_bsmt_sf  bsmt_full_bath  \
1147            NaN         479.0       1603.0         3206.0             1.0   
1456            Unf           0.0        725.0          725.0             0.0   
1547            Unf           0.0       1595.0         1595.0             0.0   
1997            Unf           0.0        936.0          936.0             0.0   

      bsmt_half_bath  
1147             0.0  
1456             0.0  
1547             0.0  
1997             0.0

**Analysis: Successfully indicated 'NA' (No basement) and value zero for basement features when total basement area is zero.**

* The basement features has successfully replaced the missing values with 'NA' for No basement and value zero for full bath and half bath in basement when total basement area is zero. This includes for index 1327 for all basement features.
* There are additional missing values:-
    * bsmt_exposure has 3 additional missing values at Index 1456, 1547, 1997. As these three missing values in has similar characteristics, we can investigate if there are a similar trend in the bsmt exposure with the characteristics of "bsmt_qual" is 'Gd', 'bsmt_cond' is 'TA', 'bsmtfin_type_1 is 'Unf', 'bsmt_unf_sf' more than 700 sqft, 'bsmt_full_bath' is 0 and 'bsmt_half_bath' is 0.
    * Index 1147 for column bsmtfin_type_2 has 1 missing value. We can investigate the similar trend with other basement features.

**bsmt_exposure missing values**

In [38]:
# Using the similar characteristics across the three missing values to filter and observe similar trends
housing_data.loc[(housing_data["bsmt_qual"]=='Gd') &
                 (housing_data["bsmt_cond"]=='TA') &
                 (housing_data["bsmtfin_type_1"]=='Unf') &
                 (housing_data["bsmt_unf_sf"]>700) &
                 (housing_data["bsmt_full_bath"]== 0) &
                 (housing_data["bsmt_half_bath"]== 0),
                  ["bsmt_qual","bsmt_cond","bsmt_exposure",
                   "bsmtfin_type_1","bsmtfin_sf_1","bsmtfin_type_2", 
                   "bsmtfin_sf_2", "bsmt_unf_sf", "total_bsmt_sf", 
                   "bsmt_full_bath", "bsmt_half_bath"]].head()

bsmt_qual bsmt_cond bsmt_exposure bsmtfin_type_1  bsmtfin_sf_1  \
31        Gd        TA            No            Unf           0.0   
47        Gd        TA            No            Unf           0.0   
49        Gd        TA            No            Unf           0.0   
67        Gd        TA            No            Unf           0.0   
73        Gd        TA            No            Unf           0.0   

   bsmtfin_type_2  bsmtfin_sf_2  bsmt_unf_sf  total_bsmt_sf  bsmt_full_bath  \
31            Unf           0.0        792.0          792.0             0.0   
47            Unf           0.0        776.0          776.0             0.0   
49            Unf           0.0        764.0          764.0             0.0   
67            Unf           0.0        976.0          976.0             0.0   
73            Unf           0.0        970.0          970.0             0.0   

    bsmt_half_bath  
31             0.0  
47             0.0  
49             0.0  
67             0.0  
73             0.0

In [39]:
# To count the values in bsmt_exposure when it is observed with the similar characteristics
mask = (housing_data["bsmt_qual"]=='Gd') & (housing_data["bsmt_cond"]=='TA') & (housing_data["bsmtfin_type_1"]=='Unf') & (housing_data["bsmt_unf_sf"]>700) & (housing_data["bsmt_full_bath"]== 0) & (housing_data["bsmt_half_bath"]== 0)
housing_data.groupby(mask)['bsmt_exposure'].value_counts()

       bsmt_exposure
False  No               1184
       Av                246
       Gd                195
       Mn                152
       NA                 55
True   No                155
       Av                 42
       Mn                 11
       Gd                  8
Name: bsmt_exposure, dtype: int64

**Analysis: Using the similar parameters across the three 'bsmt_exposure' missing values as criteria, the majority of the samples are labeled as No exposure**

Majority of the sample are labeled as No exposure when compared to the other ratings. Thus, we will place 'No" for these missing values.

In [40]:
# Change the missing values to 'No' using the similar characteristics across the three missing values
mask = (housing_data["bsmt_qual"]=='Gd') & (housing_data["bsmt_cond"]=='TA') & (housing_data["bsmtfin_type_1"]=='Unf') & (housing_data["bsmt_unf_sf"]>700) & (housing_data["bsmt_full_bath"]== 0) & (housing_data["bsmt_half_bath"]== 0)
housing_data.loc[mask,"bsmt_exposure"] = housing_data.loc[mask,"bsmt_exposure"].fillna('No')

In [41]:
# To check if the missing values have been filled as 'No'
housing_data.loc[([1456, 1547, 1997]), ["bsmt_qual","bsmt_cond","bsmt_exposure",
                                      "bsmtfin_type_1","bsmtfin_sf_1","bsmtfin_type_2", 
                                      "bsmtfin_sf_2", "bsmt_unf_sf", "total_bsmt_sf", 
                                      "bsmt_full_bath", "bsmt_half_bath"]]

bsmt_qual bsmt_cond bsmt_exposure bsmtfin_type_1  bsmtfin_sf_1  \
1456        Gd        TA            No            Unf           0.0   
1547        Gd        TA            No            Unf           0.0   
1997        Gd        TA            No            Unf           0.0   

     bsmtfin_type_2  bsmtfin_sf_2  bsmt_unf_sf  total_bsmt_sf  bsmt_full_bath  \
1456            Unf           0.0        725.0          725.0             0.0   
1547            Unf           0.0       1595.0         1595.0             0.0   
1997            Unf           0.0        936.0          936.0             0.0   

      bsmt_half_bath  
1456             0.0  
1547             0.0  
1997             0.0

In [42]:
housing_data.bsmt_exposure.isnull().sum()

0

**Analysis: The 'bsmt_exposure' three missing values have been filled as 'No'.**

**bsmtfin_type_2 missing values**

In [43]:
# To check the bsmtfin_type_2 missing values
housing_data.loc[(housing_data["bsmtfin_type_2"].isnull()),
                  ["bsmt_qual","bsmt_cond","bsmt_exposure",
                   "bsmtfin_type_1","bsmtfin_sf_1","bsmtfin_type_2", 
                   "bsmtfin_sf_2", "bsmt_unf_sf", "total_bsmt_sf", 
                   "bsmt_full_bath", "bsmt_half_bath"]]

bsmt_qual bsmt_cond bsmt_exposure bsmtfin_type_1  bsmtfin_sf_1  \
1147        Gd        TA            No            GLQ        1124.0   

     bsmtfin_type_2  bsmtfin_sf_2  bsmt_unf_sf  total_bsmt_sf  bsmt_full_bath  \
1147            NaN         479.0       1603.0         3206.0             1.0   

      bsmt_half_bath  
1147             0.0

In [44]:
# Using the similar characteristics for the bsmtfin_type_2 to filter and observe similar trends
housing_data.loc[(housing_data["bsmt_qual"]=='Gd') &
                 (housing_data["bsmt_cond"]=='TA') &
                 (housing_data["bsmt_exposure"] == 'No') &
                 (housing_data["bsmtfin_sf_2"]>400),
                  ["bsmt_qual","bsmt_cond","bsmt_exposure",
                   "bsmtfin_type_1","bsmtfin_sf_1","bsmtfin_type_2", 
                   "bsmtfin_sf_2", "bsmt_unf_sf", "total_bsmt_sf", 
                   "bsmt_full_bath", "bsmt_half_bath"]].head()

bsmt_qual bsmt_cond bsmt_exposure bsmtfin_type_1  bsmtfin_sf_1  \
52         Gd        TA            No            BLQ         790.0   
92         Gd        TA            No            LwQ          36.0   
278        Gd        TA            No            LwQ          81.0   
285        Gd        TA            No            BLQ         299.0   
294        Gd        TA            No            ALQ         435.0   

    bsmtfin_type_2  bsmtfin_sf_2  bsmt_unf_sf  total_bsmt_sf  bsmt_full_bath  \
52             LwQ         469.0        133.0         1392.0             1.0   
92             GLQ         596.0        122.0          754.0             1.0   
278            GLQ         612.0         23.0          716.0             1.0   
285            LwQ         891.0          0.0         1190.0             0.0   
294            LwQ         622.0          0.0         1057.0             0.0   

     bsmt_half_bath  
52              0.0  
92              0.0  
278             0.0  
285             0.0  
294             1.0

In [45]:
# To count the values in bsmtfin_type_2 when it is observed with the similar characteristics
mask = (housing_data["bsmt_qual"]=='Gd') & (housing_data["bsmt_cond"]=='TA') &(housing_data["bsmt_exposure"] == 'No') &(housing_data["bsmtfin_sf_2"]>400)
housing_data.groupby(mask)["bsmtfin_type_2"].value_counts()

       bsmtfin_type_2
False  Unf               1749
       Rec                 78
       LwQ                 56
       NA                  55
       BLQ                 47
       ALQ                 32
       GLQ                 19
True   GLQ                  4
       LwQ                  4
       ALQ                  3
       Rec                  2
       BLQ                  1
Name: bsmtfin_type_2, dtype: int64

**Analysis: Using the similar parameters for this missing value as criteria, the median will be used to fill in the missing values**

As there is a equal proportion of values labeled across these criteria, the median wil be used to fill in the missing values. Thus, we will place 'ALQ" for this missing value.

In [46]:
# Change the missing values to 'ALQ' using the similar characteristics across the missing value
mask = (housing_data["bsmt_qual"]=='Gd') & (housing_data["bsmt_cond"]=='TA') &(housing_data["bsmt_exposure"] == 'No') &(housing_data["bsmtfin_sf_2"]>400)
housing_data.loc[mask,"bsmtfin_type_2"] = housing_data.loc[mask,"bsmtfin_type_2"].fillna('ALQ')

In [47]:
# To check if the missing values have been filled as 'No'
housing_data.loc[([1147]), ["bsmt_qual","bsmt_cond","bsmt_exposure","bsmtfin_type_1","bsmtfin_sf_1","bsmtfin_type_2", 
                            "bsmtfin_sf_2", "bsmt_unf_sf", "total_bsmt_sf", "bsmt_full_bath", "bsmt_half_bath"]]

bsmt_qual bsmt_cond bsmt_exposure bsmtfin_type_1  bsmtfin_sf_1  \
1147        Gd        TA            No            GLQ        1124.0   

     bsmtfin_type_2  bsmtfin_sf_2  bsmt_unf_sf  total_bsmt_sf  bsmt_full_bath  \
1147            ALQ         479.0       1603.0         3206.0             1.0   

      bsmt_half_bath  
1147             0.0

In [48]:
housing_data.bsmtfin_type_2.isnull().sum()

0

**Analysis: The 'bsmtfin_type_2' missing values have been filled as 'ALQ'.**

In [49]:
housing_data.loc[(housing_data["bsmt_qual"].isnull())|
                 (housing_data["bsmt_cond"].isnull())|
                 (housing_data["bsmt_exposure"].isnull())|
                 (housing_data["bsmtfin_type_1"].isnull())|
                 (housing_data["bsmtfin_type_2"].isnull())|
                 (housing_data["bsmt_full_bath"].isnull())|
                 (housing_data["bsmt_half_bath"].isnull())|
                 (housing_data["bsmtfin_sf_1"].isnull())|
                 (housing_data["bsmtfin_sf_2"].isnull())|
                 (housing_data["bsmt_unf_sf"].isnull())|
                 (housing_data["total_bsmt_sf"].isnull()), 
                 ["bsmt_qual","bsmt_cond","bsmt_exposure",
                  "bsmtfin_type_1","bsmtfin_sf_1","bsmtfin_type_2", 
                  "bsmtfin_sf_2", "bsmt_unf_sf", "total_bsmt_sf", 
                  "bsmt_full_bath", "bsmt_half_bath"]].head()

Empty DataFrame
Columns: [bsmt_qual, bsmt_cond, bsmt_exposure, bsmtfin_type_1, bsmtfin_sf_1, bsmtfin_type_2, bsmtfin_sf_2, bsmt_unf_sf, total_bsmt_sf, bsmt_full_bath, bsmt_half_bath]
Index: []

**Summary: The basement features for housing_data missing values has been filled.**

**Encode ordinal basement features for housing_data**

The ordinal basement features will be encoded to numerical form for future analysis.

In [50]:
# Mapping the ordinal basement features for housing_data for an ordinal encoding
housing_data["bsmt_qual"] = housing_data["bsmt_qual"].map({'NA': 0, 'Po': 1, 'Fa': 2, "TA": 3, "Gd": 4, "Ex":5})
housing_data["bsmt_cond"] = housing_data["bsmt_cond"].map({'NA': 0, 'Po': 1, 'Fa': 2, "TA": 3, "Gd": 4, "Ex":5})
housing_data["bsmt_exposure"] = housing_data["bsmt_exposure"].map({'NA': 0, 'No': 1, 'Mn': 2, "Av": 3, "Gd": 4})
housing_data["bsmtfin_type_1"] = housing_data["bsmtfin_type_1"].map({'NA': 0, 'Unf': 1, 'LwQ': 2, "Rec": 3, "BLQ": 4, "ALQ": 5, "GLQ": 6})
housing_data["bsmtfin_type_2"] = housing_data["bsmtfin_type_2"].map({'NA': 0, 'Unf': 1, 'LwQ': 2, "Rec": 3, "BLQ": 4, "ALQ": 5, "GLQ": 6})
print(f"The bsmt_qual unique characters is {(housing_data.bsmt_qual.unique())}")
print(f"The bsmt_cond unique characters is {(housing_data.bsmt_cond.unique())}")
print(f"The bsmt_exposure unique characters is {(housing_data.bsmt_exposure.unique())}")
print(f"The bsmtfin_type_1 unique characters is {(housing_data.bsmtfin_type_1.unique())}")
print(f"The bsmtfin_type_2 unique characterbs is {(housing_data.bsmtfin_type_2.unique())}")

The bsmt_qual unique characters is [3 4 2 0 5 1]
The bsmt_cond unique characters is [3 4 0 2 1 5]
The bsmt_exposure unique characters is [1 4 3 0 2]
The bsmtfin_type_1 unique characters is [6 1 5 3 0 4 2]
The bsmtfin_type_2 unique characterbs is [1 3 0 4 6 2 5]


**2. test_housing_data**

In [51]:
# Checking the null for columns related to basement
test_housing_data.loc[(test_housing_data["bsmt_qual"].isnull())| 
                      (test_housing_data["bsmt_cond"].isnull())|
                      (test_housing_data["bsmt_exposure"].isnull())| 
                      (test_housing_data["bsmtfin_type_1"].isnull())|
                      (test_housing_data["bsmtfin_type_2"].isnull())|
                      (test_housing_data["bsmt_full_bath"].isnull())|
                      (test_housing_data["bsmt_half_bath"].isnull())|
                      (test_housing_data["bsmtfin_sf_1"].isnull())|
                      (test_housing_data["bsmtfin_sf_2"].isnull())|
                      (test_housing_data["bsmt_unf_sf"].isnull())|
                      (test_housing_data["total_bsmt_sf"].isnull()),
                      ["bsmt_qual","bsmt_cond","bsmt_exposure", 
                       "bsmtfin_type_1","bsmtfin_sf_1","bsmtfin_type_2", 
                       "bsmtfin_sf_2", "bsmt_unf_sf", "total_bsmt_sf", 
                       "bsmt_full_bath", "bsmt_half_bath"]].head()

bsmt_qual bsmt_cond bsmt_exposure bsmtfin_type_1  bsmtfin_sf_1  \
15        NaN       NaN           NaN            NaN             0   
37        NaN       NaN           NaN            NaN             0   
76        NaN       NaN           NaN            NaN             0   
78        NaN       NaN           NaN            NaN             0   
112       NaN       NaN           NaN            NaN             0   

    bsmtfin_type_2  bsmtfin_sf_2  bsmt_unf_sf  total_bsmt_sf  bsmt_full_bath  \
15             NaN             0            0              0               0   
37             NaN             0            0              0               0   
76             NaN             0            0              0               0   
78             NaN             0            0              0               0   
112            NaN             0            0              0               0   

     bsmt_half_bath  
15                0  
37                0  
76                0  
78                0  
112               0

**Analysis: Majority of the basement features have missing values when total basement area (total_bsmt_sf) is zero.**

When total_bsmt_sf (basement area) is 0, this suggests that there should be no other basement features. For  bsmt_qual, bsmt_cond, bsmt_exposure, bsmtfin_type_1, bsmtfin_type_2, the missing values will be inputed as 'NA' for No basement when the total_bsmt_sf is 0.

In [52]:
"""Change the missing values in bsmt_qual, bsmt_cond, bsmt_exposure, bsmtfin_type_1, bsmtfin_type_2 column to 
'NA' while for bsmt_full_bath and bsmt_half_bath columns to 0 when total_bsmt_sf is 0"""
modify_with_criteria_onenull_onezero(test_housing_data, "bsmt_qual", "total_bsmt_sf", 'NA')
modify_with_criteria_onenull_onezero(test_housing_data, "bsmt_cond", "total_bsmt_sf", 'NA')
modify_with_criteria_onenull_onezero(test_housing_data, "bsmt_exposure", "total_bsmt_sf", 'NA')
modify_with_criteria_onenull_onezero(test_housing_data, "bsmtfin_type_1", "total_bsmt_sf", 'NA')
modify_with_criteria_onenull_onezero(test_housing_data, "bsmtfin_type_2", "total_bsmt_sf", 'NA')

'The missing values has successfully changed.'

In [53]:
# Check for missing values in basement related columns
test_housing_data.loc[(test_housing_data["bsmt_qual"].isnull())| 
                      (test_housing_data["bsmt_cond"].isnull())|
                      (test_housing_data["bsmt_exposure"].isnull())| 
                      (test_housing_data["bsmtfin_type_1"].isnull())|
                      (test_housing_data["bsmtfin_type_2"].isnull())|
                      (test_housing_data["bsmt_full_bath"].isnull())|
                      (test_housing_data["bsmt_half_bath"].isnull())|
                      (test_housing_data["bsmtfin_sf_1"].isnull())|
                      (test_housing_data["bsmtfin_sf_2"].isnull())|
                      (test_housing_data["bsmt_unf_sf"].isnull())|
                      (test_housing_data["total_bsmt_sf"].isnull()),
                      ["bsmt_qual","bsmt_cond","bsmt_exposure", 
                       "bsmtfin_type_1","bsmtfin_sf_1","bsmtfin_type_2", 
                       "bsmtfin_sf_2", "bsmt_unf_sf", "total_bsmt_sf", 
                       "bsmt_full_bath", "bsmt_half_bath"]].head()

Empty DataFrame
Columns: [bsmt_qual, bsmt_cond, bsmt_exposure, bsmtfin_type_1, bsmtfin_sf_1, bsmtfin_type_2, bsmtfin_sf_2, bsmt_unf_sf, total_bsmt_sf, bsmt_full_bath, bsmt_half_bath]
Index: []

**Analysis: Successfully indicated 'NA' (No basement) and value zero for basement features when total basement area is zero.**

* The basement features has successfully replaced the missing values with 'NA' for No basement and value zero for full bath and half bath in basement when total basement area is zero.

**Summary: Both housing_data and test_housing_data missing values for basement features have been filled**

**Encode ordinal basement features for housing_data**

The ordinal basement features will be encoded to numerical form for future analysis.

In [54]:
# Mapping the ordinal basement features for housing_data for an ordinal encoding
test_housing_data["bsmt_qual"] = test_housing_data["bsmt_qual"].map({'NA': 0, 'Po': 1, 'Fa': 2, "TA": 3, "Gd": 4, "Ex":5})
test_housing_data["bsmt_cond"] = test_housing_data["bsmt_cond"].map({'NA': 0, 'Po': 1, 'Fa': 2, "TA": 3, "Gd": 4, "Ex":5})
test_housing_data["bsmt_exposure"] = test_housing_data["bsmt_exposure"].map({'NA': 0, 'No': 1, 'Mn': 2, "Av": 3, "Gd": 4})
test_housing_data["bsmtfin_type_1"] = test_housing_data["bsmtfin_type_1"].map({'NA': 0, 'Unf': 1, 'LwQ': 2, "Rec": 3, "BLQ": 4, "ALQ": 5, "GLQ": 6})
test_housing_data["bsmtfin_type_2"] = test_housing_data["bsmtfin_type_2"].map({'NA': 0, 'Unf': 1, 'LwQ': 2, "Rec": 3, "BLQ": 4, "ALQ": 5, "GLQ": 6})
print(f"The bsmt_qual unique characters is {(test_housing_data.bsmt_qual.unique())}")
print(f"The bsmt_cond unique characters is {(test_housing_data.bsmt_cond.unique())}")
print(f"The bsmt_exposure unique characters is {(test_housing_data.bsmt_exposure.unique())}")
print(f"The bsmtfin_type_1 unique characters is {(test_housing_data.bsmtfin_type_1.unique())}")
print(f"The bsmtfin_type_2 unique characterbs is {(test_housing_data.bsmtfin_type_2.unique())}")

The bsmt_qual unique characters is [2 4 3 5 0 1]
The bsmt_cond unique characters is [3 4 0 2]
The bsmt_exposure unique characters is [1 3 0 2 4]
The bsmtfin_type_1 unique characters is [1 6 4 3 5 0 2]
The bsmtfin_type_2 unique characterbs is [1 2 0 5 6 3 4]


### 2.3.4.3 Fence missing values

In [55]:
# missing values of fence
housing_data.fence.isnull().sum()

1651

In [56]:
# The unique values in fence
housing_data.fence.unique()

array([nan, 'MnPrv', 'GdPrv', 'GdWo', 'MnWw'], dtype=object)

**Analysis: The missing value of 'NA' option might suggests the missing values are no fence."**

There are five options for the category fence, which is 'GdPrv' for Good Privacy, 'MnPrv' for Minimum Privacy, 'GdWo' for Good Wood, 'MnWw' for Minimum Wood/Wire and 'NA' for No fence. Thus, the missing values will be indicated as 'NA' and will perform ordinal encoding to the values.

In [57]:
# Fill the missing values with 'NA' and perform a ordinal encoding to the values.
housing_data.fence = housing_data.fence.fillna('NA')
housing_data["fence"] = housing_data["fence"].map({'NA': 0, 'MnWw': 1, 'GdWo': 2, "MnPrv": 3, "GdPrv": 4})
print(f"The fence unique characters is {(housing_data.fence.unique())}")

The fence unique characters is [0 3 4 2 1]


**2. test_housing_data**

In [58]:
# missing values of fence
test_housing_data.fence.isnull().sum()

706

In [59]:
# The unique values in fence
test_housing_data.fence.unique()

array([nan, 'MnPrv', 'GdPrv', 'GdWo', 'MnWw'], dtype=object)

**Analysis: Similar to housing_data, the missing value of 'NA' option might suggests the missing values are no fence."**

Similarly, the 'NA' for No fence is missing out of the five options, which might suggests it to be no fence. Thus, the missing values will be indicated as 'NA' and will perform an ordinal encoding to the values.

In [60]:
# Fill the missing values with 'NA' and perform an ordinal encoding to the values.
test_housing_data.fence = test_housing_data.fence.fillna('NA')
test_housing_data["fence"] = test_housing_data["fence"].map({'NA': 0, 'MnWw': 1, 'GdWo': 2, "MnPrv": 3, "GdPrv": 4})
print(f"The fence unique characters is {(test_housing_data.fence.unique())}")

The fence unique characters is [0 3 4 2 1]


**Summary: Both housing_data and test_housing_data for fence missing values has been change to 'NA' and perform an ordinal encoding to the values.**

### 2.3.4.4 Fireplace missing values

**1. housing_data**

In [61]:
# Checking the null for columns related to fireplace
housing_data.loc[(housing_data["fireplace_qu"].isnull()) & (housing_data["fireplaces"] == 0), ["fireplaces", "fireplace_qu"]].head()

fireplaces fireplace_qu
0           0          NaN
2           0          NaN
3           0          NaN
4           0          NaN
6           0          NaN

**Analysis: Fireplace quality column have missing values when number of fireplaces is zero.**

There are a significant amount of missing values for fireplace_qu column.
When the number of fireplaces is 0, this suggests that there will be no rating for fireplace quality (fireplace_qu) and will be indicated as 'NA' for No Fireplace and perform an ordinal encording for the values.

In [62]:
# Change NaN in fireplace_qu column to 'ANA' when fireplaces is 0 and perform encoding for the values
modify_with_criteria_onenull_onezero(housing_data, "fireplace_qu", "fireplaces", 'NA')
housing_data.loc[(housing_data["fireplace_qu"].isnull()), ["fireplaces", "fireplace_qu"]]

Empty DataFrame
Columns: [fireplaces, fireplace_qu]
Index: []

In [63]:
# Perform an ordinal encoding to the values.
housing_data["fireplace_qu"] = housing_data["fireplace_qu"].map({'NA': 0, 'Po': 1, 'Fa': 2, "TA": 3, "Gd": 4, "Ex": 5})
print(f"The fireplace_qu unique characters is {(housing_data.fireplace_qu.unique())}")

The fireplace_qu unique characters is [0 3 4 1 5 2]


**2. test_housing_data**

In [64]:
# Checking the null for columns related to fireplace
test_housing_data.loc[(test_housing_data["fireplace_qu"].isnull()) & (test_housing_data["fireplaces"] == 0), ["fireplaces", "fireplace_qu"]].head()

fireplaces fireplace_qu
0           0          NaN
1           0          NaN
3           0          NaN
5           0          NaN
6           0          NaN

**Analysis: Fireplace quality column have missing values when number of fireplaces is zero.**

Similarly to housing_data, there are a significant amount of missing values for fireplace_qu column.
When the number of fireplaces is 0, this suggests that there will be no rating for fireplace quality (fireplace_qu) and will be indicated as 'NA' for No Fireplace when fireplaces is zero as well as perform an ordinal encoding for the values.

In [65]:
# Change NaN in fireplace_qu column to 'NA' when fireplaces is 0
modify_with_criteria_onenull_onezero(test_housing_data, "fireplace_qu", "fireplaces", 'NA')
test_housing_data.loc[(test_housing_data["fireplace_qu"].isnull()), ["fireplaces", "fireplace_qu"]]

Empty DataFrame
Columns: [fireplaces, fireplace_qu]
Index: []

In [66]:
# Perform an ordinal encoding to the values.
test_housing_data["fireplace_qu"] = test_housing_data["fireplace_qu"].map({'NA': 0, 'Po': 1, 'Fa': 2, "TA": 3, "Gd": 4, "Ex": 5})
print(f"The fireplace_qu unique characters is {(test_housing_data.fireplace_qu.unique())}")

The fireplace_qu unique characters is [0 4 2 3 1 5]


**Summary: Both housing_data and test_housing_data for fireplace_qu missing values has been change to 'NA' and perform an ordinal encoding to the values.**

### 2.3.4.5 Lot frontage missing values

**1. housing_data**

In [67]:
# To check the missing values in lot_frontage column
housing_data.loc[(housing_data["lot_frontage"].isnull()),['lot_shape',"lot_frontage", "lot_config", "lot_area"]].head()

lot_shape  lot_frontage lot_config  lot_area
0        IR1           NaN    CulDSac     13517
7        IR1           NaN     Inside     12160
8        Reg           NaN     Inside     15783
23       IR1           NaN     Inside      7980
27       IR1           NaN     Inside     11700

In [68]:
# To check the amount of missing values in lot frontage 
housing_data.lot_frontage.isnull().sum()

330

In [69]:
# To check the distribution and mean of lot_frontage column
housing_data.lot_frontage.describe()

count    1721.000000
mean       69.055200
std        23.260653
min        21.000000
25%        58.000000
50%        68.000000
75%        80.000000
max       313.000000
Name: lot_frontage, dtype: float64

**Analysis: As there is a significant amount of missing values in lot_frontage and it is a continuous value, the mean will be used to fill in the missing values**

In [70]:
# Change the missing values to 'mean' using the similar characteristics across the missing value
housing_data["lot_frontage"] = housing_data["lot_frontage"].fillna((np.mean(housing_data["lot_frontage"])))
housing_data.lot_frontage.isnull().sum()

0

**Analysis: The lot_frontage missing values have been filled with the mean of lot_frontage.**

**2. test_housing_data**

In [71]:
# To check the missing values in lot_frontage column
test_housing_data.loc[(test_housing_data["lot_frontage"].isnull()),['lot_shape',"lot_frontage", "lot_config", "lot_area"]].head()

lot_shape  lot_frontage lot_config  lot_area
1        IR1           NaN     Inside      9662
4        IR1           NaN     Inside      9500
7        IR1           NaN    CulDSac      9286
13       Reg           NaN     Inside      7976
20       IR1           NaN     Inside      8246

In [72]:
# To check the amount of missing values in lot frontage 
test_housing_data.lot_frontage.isnull().sum()

160

In [73]:
# To check the distribution and mean of lot_frontage column
test_housing_data.lot_frontage.describe()

count    718.000000
mean      69.545961
std       23.533945
min       21.000000
25%       59.000000
50%       68.000000
75%       80.000000
max      182.000000
Name: lot_frontage, dtype: float64

**Analysis: Similarly to housing_data, the mean will be used to fill in the missing values as there is a significant amount of missing values in lot_frontage**

In [74]:
# Change the missing values to 'mean' using the similar characteristics across the missing value
test_housing_data["lot_frontage"] = test_housing_data["lot_frontage"].fillna((np.mean(test_housing_data["lot_frontage"])))
test_housing_data.lot_frontage.isnull().sum()

0

**Analysis: The lot_frontage missing values have been filled with the mean of lot_frontage.**

**Summary: Both housing_data and test_housing_data for lot_frontage has been filled with the mean of lot_frontage for the missing values.**

### 2.3.4.6 Garage missing values

**1. housing_data**

In [75]:
# Checking the null for columns related to garage
housing_data.loc[(housing_data["garage_type"].isnull())|
                 (housing_data["garage_yr_blt"].isnull())|
                 (housing_data["garage_finish"].isnull())|
                 (housing_data["garage_cars"].isnull())|
                 (housing_data["garage_area"].isnull())|
                 (housing_data["garage_qual"].isnull())|
                 (housing_data["garage_cond"].isnull()), 
                 ["garage_type","garage_yr_blt","garage_finish","garage_cars",
                  "garage_area","garage_qual", "garage_cond"]].head()

garage_type  garage_yr_blt garage_finish  garage_cars  garage_area  \
28          NaN            NaN           NaN          0.0          0.0   
53          NaN            NaN           NaN          0.0          0.0   
65          NaN            NaN           NaN          0.0          0.0   
79          NaN            NaN           NaN          0.0          0.0   
101         NaN            NaN           NaN          0.0          0.0   

    garage_qual garage_cond  
28          NaN         NaN  
53          NaN         NaN  
65          NaN         NaN  
79          NaN         NaN  
101         NaN         NaN

**Analysis: Majority of the garage features have missing values when garage area (garage_area) is zero.**

1. When garage area (garage_area) is 0, this suggests that there should be no other garage features.

2. For garage_finish, garage_qual and garage_cond, the missing values will be inputed as 'NA' for No garage while garage_yr_blt is 'None' and garage_type as '1NA' when the garage_area is 0. 

3. Index 1712 has no garage information for all garage features except for garage_type (Detchd). As all values are missing, this might suggests that there is no garage for this property. Thus, the missing values will be inputed as 'NA' for the respective columns.

In [76]:
# Change the index 1712 missing values for garage_cars and garage_area to 0
housing_data.loc[[1712],'garage_cars'] = housing_data.loc[[1712],'garage_cars'].fillna(0)
housing_data.loc[[1712],'garage_area'] = housing_data.loc[[1712],'garage_area'].fillna(0)
housing_data.loc[[1712], ['garage_cars', 'garage_area']].head()

garage_cars  garage_area
1712          0.0          0.0

In [77]:
"""Change the missing values in garage_type, garage_finish, garage_qual, garage_cond column to 
'NA' when garage_area is 0"""
modify_with_criteria_onenull_onezero(housing_data, "garage_type", "garage_area", '1NA')
modify_with_criteria_onenull_onezero(housing_data, "garage_yr_blt", "garage_area", 'None')
modify_with_criteria_onenull_onezero(housing_data, "garage_finish", "garage_area", 'NA')
modify_with_criteria_onenull_onezero(housing_data, "garage_qual", "garage_area", 'NA')
modify_with_criteria_onenull_onezero(housing_data, "garage_cond", "garage_area", 'NA')

'The missing values has successfully changed.'

In [78]:
# Checking the null for columns related to garage
housing_data.loc[(housing_data["garage_type"].isnull())|
                 (housing_data["garage_yr_blt"].isnull())|
                 (housing_data["garage_finish"].isnull())|
                 (housing_data["garage_cars"].isnull())|
                 (housing_data["garage_area"].isnull())|
                 (housing_data["garage_qual"].isnull())|
                 (housing_data["garage_cond"].isnull()), 
                 ["garage_type","garage_yr_blt","garage_finish","garage_cars",
                  "garage_area","garage_qual", "garage_cond"]].head()

Empty DataFrame
Columns: [garage_type, garage_yr_blt, garage_finish, garage_cars, garage_area, garage_qual, garage_cond]
Index: []

**Analysis: Successfully indicated 'NA' (No garage) for garage features when garage area (garage_area) is zero including index 1712.**

**Encode ordinal garage features for housing_data**

The ordinal garage features will be encoded to numerical form for future analysis.

In [79]:
# Mapping the ordinal garage features for housing_data for an ordinal encoding
housing_data["garage_qual"] = housing_data["garage_qual"].map({'NA': 0, 'Po': 1, 'Fa': 2, "TA": 3, "Gd": 4, "Ex":5})
housing_data["garage_cond"] = housing_data["garage_cond"].map({'NA': 0, 'Po': 1, 'Fa': 2, "TA": 3, "Gd": 4, "Ex":5})
housing_data["garage_finish"] = housing_data["garage_finish"].map({'NA': 0, 'Unf': 1, 'RFn': 2, "Fin": 3})

print(f"The garage_qual unique characters is {(housing_data.garage_qual.unique())}")
print(f"The garage_cond unique characters is {(housing_data.garage_cond.unique())}")
print(f"The garage_finish unique characters is {(housing_data.garage_finish.unique())}")

The garage_qual unique characters is [3 2 0 4 5 1]
The garage_cond unique characters is [3 2 0 1 4 5]
The garage_finish unique characters is [2 1 3 0]


The nominal garage feature (garage_type) will be dummy encoded for future analysis

In [80]:
# Perform a dummy encoding to the values.
housing_data = pd.get_dummies(columns = ["garage_type"], drop_first = True, data = housing_data)
housing_data.head()

ms_subclass ms_zoning  lot_frontage  lot_area street lot_shape  \
0           60        RL       69.0552     13517   Pave       IR1   
1           60        RL       43.0000     11492   Pave       IR1   
2           20        RL       68.0000      7922   Pave       Reg   
3           60        RL       73.0000      9802   Pave       Reg   
4           50        RL       82.0000     14235   Pave       IR1   

  land_contour utilities lot_config land_slope  ... sale_type saleprice  \
0          Lvl    AllPub    CulDSac        Gtl  ...       WD     130500   
1          Lvl    AllPub    CulDSac        Gtl  ...       WD     220000   
2          Lvl    AllPub     Inside        Gtl  ...       WD     109000   
3          Lvl    AllPub     Inside        Gtl  ...       WD     174000   
4          Lvl    AllPub     Inside        Gtl  ...       WD     138500   

  alley_Grvl alley_Pave garage_type_2Types  garage_type_Attchd  \
0          0          0                  0                   1   
1          0          0                  0                   1   
2          0          0                  0                   0   
3          0          0                  0                   0   
4          0          0                  0                   0   

   garage_type_Basment  garage_type_BuiltIn  garage_type_CarPort  \
0                    0                    0                    0   
1                    0                    0                    0   
2                    0                    0                    0   
3                    0                    1                    0   
4                    0                    0                    0   

  garage_type_Detchd  
0                  0  
1                  0  
2                  1  
3                  0  
4                  1  

[5 rows x 85 columns]

**2. test_housing_data**

In [81]:
# Checking the null for columns related to garage
test_housing_data.loc[(test_housing_data["garage_type"].isnull())|(test_housing_data["garage_yr_blt"].isnull())|
                      (test_housing_data["garage_finish"].isnull())|(test_housing_data["garage_cars"].isnull())|
                      (test_housing_data["garage_area"].isnull())|(test_housing_data["garage_qual"].isnull())|
                      (test_housing_data["garage_cond"].isnull()), 
                      ["garage_type","garage_yr_blt","garage_finish","garage_cars",
                       "garage_area","garage_qual", "garage_cond"]].head()

garage_type  garage_yr_blt garage_finish  garage_cars  garage_area  \
29          NaN            NaN           NaN            0            0   
45          NaN            NaN           NaN            0            0   
66          NaN            NaN           NaN            0            0   
68          NaN            NaN           NaN            0            0   
105         NaN            NaN           NaN            0            0   

    garage_qual garage_cond  
29          NaN         NaN  
45          NaN         NaN  
66          NaN         NaN  
68          NaN         NaN  
105         NaN         NaN

**Analysis: Majority of the garage features have missing values when garage area (garage_area) is zero.**

1. When garage area (garage_area) is 0, this suggests that there should be no other garage features.

2. For garage_finish, garage_qual and garage_cond, the missing values will be inputed as 'NA' for No garage while garage_yr_blt will be inputed as 'None' and garage_type will be inputed as '1NA' when the garage_area is 0. 

3. Index 764 has some garage information. We will look at similar characteristics to observe the trend.

In [82]:
"""Change the missing values in garage_type, garage_yr_blt, garage_finish, garage_qual, garage_cond column 
when garage_area is 0"""
modify_with_criteria_onenull_onezero(test_housing_data, "garage_type", "garage_area", '1NA')
modify_with_criteria_onenull_onezero(test_housing_data, "garage_yr_blt", "garage_area", 'None')
modify_with_criteria_onenull_onezero(test_housing_data, "garage_finish", "garage_area", 'NA')
modify_with_criteria_onenull_onezero(test_housing_data, "garage_qual", "garage_area", 'NA')
modify_with_criteria_onenull_onezero(test_housing_data, "garage_cond", "garage_area", 'NA')

'The missing values has successfully changed.'

**Analysis: Successfully indicated 'NA' (No garage) for garage features when garage area (garage_area) is zero**

**Index 764 with limited garage information**

In [83]:
# Checking the null for columns related to garage with a range of 300 to 400 for the garage_area
test_housing_data.loc[(test_housing_data["garage_cars"] == 1) & (test_housing_data["garage_type"] == "Detchd") & 
                      (test_housing_data["garage_area"]>300) & (test_housing_data["garage_area"]<400), 
                      ["garage_type","garage_yr_blt","garage_finish","garage_cars", 
                       "garage_area","garage_qual", "garage_cond", "year_built", "year_remod"]].head()

garage_type garage_yr_blt garage_finish  garage_cars  garage_area  \
6       Detchd          1959           Unf            1          308   
25      Detchd          1989           Unf            1          352   
82      Detchd          2004           Unf            1          336   
91      Detchd          1950           Unf            1          384   
95      Detchd          1927           Unf            1          374   

   garage_qual garage_cond  year_built  year_remod  
6           TA          TA        1958        2006  
25          TA          TA        1972        1972  
82          TA          TA        1930        2005  
91          Fa          TA        1910        2000  
95          TA          TA        1927        1950

In [84]:
# To count the values in garage_finish when it is observed with the similar characteristics
mask = (test_housing_data["garage_cars"] == 1) & (test_housing_data["garage_type"] == "Detchd") & (test_housing_data["garage_area"]>300) & (test_housing_data["garage_area"]<400)
test_housing_data.groupby(mask)['garage_finish'].value_counts()

       garage_finish
False  Unf              347
       RFn              232
       Fin              217
       NA                44
True   Unf               35
       Fin                1
       RFn                1
Name: garage_finish, dtype: int64

In [85]:
# To count the values in garage_qual when it is observed with the similar characteristics
mask = (test_housing_data["garage_cars"] == 1) & (test_housing_data["garage_type"] == "Detchd") & (test_housing_data["garage_area"]>300) & (test_housing_data["garage_area"]<400)
test_housing_data.groupby(mask)['garage_qual'].value_counts()

       garage_qual
False  TA             747
       NA              44
       Fa              40
       Gd               6
       Po               3
True   TA              35
       Fa               2
Name: garage_qual, dtype: int64

In [86]:
# To count the values in garage_cond when it is observed with the similar characteristics
mask = (test_housing_data["garage_cars"] == 1) & (test_housing_data["garage_type"] == "Detchd") & (test_housing_data["garage_area"]>300) & (test_housing_data["garage_area"]<400)
test_housing_data.groupby(mask)['garage_cond'].value_counts()

       garage_cond
False  TA             760
       NA              44
       Fa              26
       Po               6
       Gd               3
       Ex               1
True   TA              36
       Fa               1
Name: garage_cond, dtype: int64

In [87]:
# To observe the house of year built and year remod with garage_yr_blt
test_housing_data.loc[[764], ["year_built", "year_remod", "garage_yr_blt"]]

year_built  year_remod garage_yr_blt
764        1910        1983           NaN

**Analysis: Using the similar characteristic of the missing values as criteria with the garage_area set between 300-400, the garage_finish will be place "Unf", garage_qual will be palce as 'TA' and garage_cond will be placed as 'TA'**

Majority of the sample are labeled as "Unf" for garage_finish, 'TA' for garage_qual and 'TA' for garage_cond when compared to the other observations. Thus, we will place the respective value for the respective column. As for the garage_yr_blt, we wiill place the year the house was built as we do not have enough information to deduce that the house remodel includes the garage.

In [88]:
print(f" The number of missing value in garage_finish is {test_housing_data.garage_finish.isnull().sum()}")
print(f" The number of missing value in garage_qual is {test_housing_data.garage_qual.isnull().sum()}")
print(f" The number of missing value in garage_cond is {test_housing_data.garage_cond.isnull().sum()}")

 The number of missing value in garage_finish is 1
 The number of missing value in garage_qual is 1
 The number of missing value in garage_cond is 1


In [89]:
# Change the missing values using the respective values for the respctive columns
test_housing_data.loc[[764],"garage_finish"] = test_housing_data.loc[[764],"garage_finish"].fillna('Unf')
test_housing_data.loc[[764],"garage_qual"] = test_housing_data.loc[[764],"garage_qual"].fillna('TA')
test_housing_data.loc[[764],"garage_cond"] = test_housing_data.loc[[764],"garage_cond"].fillna('TA')
test_housing_data.loc[[764],"garage_yr_blt"] = test_housing_data.loc[[764],"year_built"]
test_housing_data.loc[[764], ["garage_type","garage_yr_blt","garage_finish","garage_cars", "garage_area","garage_qual", "garage_cond"]].head()

garage_type garage_yr_blt garage_finish  garage_cars  garage_area  \
764      Detchd          1910           Unf            1          360   

    garage_qual garage_cond  
764          TA          TA

In [90]:
# Checking the null for columns related to garage
test_housing_data.loc[(test_housing_data["garage_type"].isnull())|(test_housing_data["garage_yr_blt"].isnull())|
                      (test_housing_data["garage_finish"].isnull())|(test_housing_data["garage_cars"].isnull())|
                      (test_housing_data["garage_area"].isnull())|(test_housing_data["garage_qual"].isnull())|
                      (test_housing_data["garage_cond"].isnull()), 
                      ["garage_type","garage_yr_blt","garage_finish","garage_cars",
                       "garage_area","garage_qual", "garage_cond"]].head()

Empty DataFrame
Columns: [garage_type, garage_yr_blt, garage_finish, garage_cars, garage_area, garage_qual, garage_cond]
Index: []

**Analysis: The Index 764 with limited garage information missing values has been filled with relation to other similar characteristics observed from other observations.**

**Encode ordinal garage features for test_housing_data**

The ordinal garage features will be encoded to numerical form for future analysis.

In [91]:
# Mapping the ordinal garage features for housing_data for an ordinal encoding
test_housing_data["garage_qual"] = test_housing_data["garage_qual"].map({'NA': 0, 'Po': 1, 'Fa': 2, "TA": 3, "Gd": 4, "Ex":5})
test_housing_data["garage_cond"] = test_housing_data["garage_cond"].map({'NA': 0, 'Po': 1, 'Fa': 2, "TA": 3, "Gd": 4, "Ex":5})
test_housing_data["garage_finish"] = test_housing_data["garage_finish"].map({'NA': 0, 'Unf': 1, 'RFn': 2, "Fin": 3})

print(f"The garage_qual unique characters is {(test_housing_data.garage_qual.unique())}")
print(f"The garage_cond unique characters is {(test_housing_data.garage_cond.unique())}")
print(f"The garage_finish unique characters is {(test_housing_data.garage_finish.unique())}")

The garage_qual unique characters is [1 3 2 0 4]
The garage_cond unique characters is [1 3 0 2 4 5]
The garage_finish unique characters is [1 3 2 0]


The nominal garage feature (garage_type) will be dummy encoded for future analysis

In [92]:
# Perform a dummy encoding to the values.
test_housing_data = pd.get_dummies(columns = ["garage_type"], drop_first = True, data = test_housing_data)
test_housing_data.head()

ms_subclass ms_zoning  lot_frontage  lot_area street lot_shape  \
0          190        RM     69.000000      9142   Pave       Reg   
1           90        RL     69.545961      9662   Pave       IR1   
2           60        RL     58.000000     17104   Pave       IR1   
3           30        RM     60.000000      8520   Pave       Reg   
4           20        RL     69.545961      9500   Pave       IR1   

  land_contour utilities lot_config land_slope  ... yr_sold sale_type  \
0          Lvl    AllPub     Inside        Gtl  ...    2006       WD    
1          Lvl    AllPub     Inside        Gtl  ...    2006       WD    
2          Lvl    AllPub     Inside        Gtl  ...    2006       New   
3          Lvl    AllPub     Inside        Gtl  ...    2007       WD    
4          Lvl    AllPub     Inside        Gtl  ...    2009       WD    

  alley_Grvl alley_Pave garage_type_2Types  garage_type_Attchd  \
0          1          0                  0                   0   
1          0          0                  0                   1   
2          0          0                  0                   1   
3          0          0                  0                   0   
4          0          0                  0                   1   

   garage_type_Basment  garage_type_BuiltIn  garage_type_CarPort  \
0                    0                    0                    0   
1                    0                    0                    0   
2                    0                    0                    0   
3                    0                    0                    0   
4                    0                    0                    0   

  garage_type_Detchd  
0                  1  
1                  0  
2                  0  
3                  1  
4                  0  

[5 rows x 84 columns]

**Summary: Both housing_data and test_housing_data for missing values for garage features has been filled and the values have been performed an ordinal amd dummy encoding.**

### 2.3.4.7 Mas_vnr missing values

**1. housing_data**

In [93]:
# To check the missing values for mas
housing_data.loc[(housing_data["mas_vnr_type"].isnull())|
                 (housing_data["mas_vnr_area"].isnull()), 
                 ["mas_vnr_type", "mas_vnr_area"]].head()

mas_vnr_type  mas_vnr_area
22           NaN           NaN
41           NaN           NaN
86           NaN           NaN
212          NaN           NaN
276          NaN           NaN

**Analysis: Both mas_vnr_type and mas_vnr_area has no values coherently.**

It is observed that both man_vnr_type and mas_vnr_area has no values coherently. This might suggest that there are no mansory veneer in these properties resulting in both values are absence. Thus, the mas_vnr_type will be indicated as 'None' while the mas_vnr_area will be indicated as zero value.

In [94]:
# Change NaN in mas_vnr_type to 'None' and mas_vnr_area to 0..
housing_data["mas_vnr_type"] = housing_data["mas_vnr_type"].fillna('None')
housing_data["mas_vnr_area"] = housing_data["mas_vnr_area"].fillna(0)
housing_data.loc[(housing_data["mas_vnr_type"].isnull())|
                 (housing_data["mas_vnr_area"].isnull()), 
                 ["mas_vnr_type", "mas_vnr_area"]]

Empty DataFrame
Columns: [mas_vnr_type, mas_vnr_area]
Index: []

**Analysis: Successfully indicated 'None' for mas_vnr_type and zero for mas_vnr_area missing values**

**2. test_housing_data**

In [95]:
# To check the missing values for mas
test_housing_data.loc[(test_housing_data["mas_vnr_type"].isnull())| 
                      (test_housing_data["mas_vnr_area"].isnull()), 
                      ["mas_vnr_type", "mas_vnr_area"]].head()

mas_vnr_type  mas_vnr_area
865          NaN           NaN

**Analysis: Similaryly, index 865 has no values for both mas_vnr_type and mas_vnr_area coherently.**

Thus, this might suggest that there are no mansory veneer in this property resulting in both values are absence. Thus, the mas_vnr_type will be indicated as 'None' while the mas_vnr_area will be indicated as zero value.

In [96]:
# Change NaN in mas_vnr_type to 'None' and mas_vnr_area to 0..
test_housing_data["mas_vnr_type"] = test_housing_data["mas_vnr_type"].fillna('None')
test_housing_data["mas_vnr_area"] = test_housing_data["mas_vnr_area"].fillna(0)
test_housing_data.loc[(test_housing_data["mas_vnr_type"].isnull())|
                      (test_housing_data["mas_vnr_area"].isnull()), 
                      ["mas_vnr_type", "mas_vnr_area"]]

Empty DataFrame
Columns: [mas_vnr_type, mas_vnr_area]
Index: []

**Analysis: Successfully indicated 'None' for mas_vnr_type and zero for mas_vnr_area missing values**

**Summary: Both housing_data and test_housing_data for missing values for masonry veneer features has been filled.**

### 2.3.4.8 Pool missing values

**1. housing_data**

In [97]:
# Checking the missing values for pool_qc
housing_data.loc[(housing_data["pool_qc"].isnull()), ['pool_qc', 'pool_area']].head()

pool_qc  pool_area
0     NaN          0
1     NaN          0
2     NaN          0
3     NaN          0
4     NaN          0

**Analysis: Pool quality (pool_qc) column have missing values when pool area is zero.**

There are a significant amount of missing values for pool quality (pool_qc) column.
When the pool area is 0, this suggests that there will be no rating for pool quality and will be indicated as 'NA' for No Pool.
For pool_qc having NaN, it will be converted to 'NA' if pool_area is 0.

In [98]:
# Change NaN in pool_qc column to 'NA' when pool_area is zero.
modify_with_criteria_onenull_onezero(housing_data, "pool_qc", "pool_area", 'NA')
housing_data.loc[(housing_data["pool_qc"].isnull()), ['pool_qc', 'pool_area']]

Empty DataFrame
Columns: [pool_qc, pool_area]
Index: []

**Analysis: Successfully indicated 'NA' (No pool) in pool quality (pool_qc) column when pool area is zero.**

There are no missing values left in pool_qc column.

**Encode ordinal pool_qc for housing_data**

The ordinal pool will be encoded to numerical form for future analysis.

In [99]:
# Mapping the ordinal pool features for housing_data for encoding
housing_data["pool_qc"] = housing_data["pool_qc"].map({'NA': 0, 'Fa': 1, "TA": 2, "Gd": 3, "Ex":4})

print(f"The pool_qc unique characters is {(housing_data.pool_qc.unique())}")

The pool_qc unique characters is [0 1 3 4 2]


**2. test_housing_data**

In [100]:
test_housing_data.loc[(test_housing_data["pool_qc"].isnull()), ['pool_qc', 'pool_area']].head()

pool_qc  pool_area
0     NaN          0
1     NaN          0
2     NaN          0
3     NaN          0
4     NaN          0

**Analysis: Pool quality (pool_qc) column have missing values when pool area is zero.**

There are a significant amount of missing values for pool quality (pool_qc) column.
When the pool area is 0, this suggests that there will be no rating for pool quality and will be indicated as 'NA' for No Pool.
For pool_qc having NaN, it will be converted to 'NA' if pool_area is 0.

In [101]:
# Change NaN in pool_qc column to 'NA' when pool_area is zero.
modify_with_criteria_onenull_onezero(test_housing_data, "pool_qc", "pool_area", 'NA')
test_housing_data.loc[(test_housing_data["pool_qc"].isnull()), ['pool_qc', 'pool_area']]

Empty DataFrame
Columns: [pool_qc, pool_area]
Index: []

**Analysis: Successfully indicated 'NA' (No pool) in pool quality (pool_qc) column when pool area is zero.**

There are no missing values left in pool_qc column.

**Encode ordinal pool_qc for test_housing_data**

The ordinal pool will be encoded to numerical form for future analysis.

In [102]:
# Mapping the ordinal pool features for test_housing_data for encoding
test_housing_data["pool_qc"] = test_housing_data["pool_qc"].map({'NA': 0, 'Fa': 1, "TA": 2, "Gd": 3, "Ex":4})

print(f"The pool_qc unique characters is {(test_housing_data.pool_qc.unique())}")

The pool_qc unique characters is [0 4 2]


**Summary: Both housing_data and test_housing_data for missing values for pool features has been filled and the values are encoded.**

### 2.3.4.9 Electrical missing values (test_housing_data only)

In [103]:
# To check the electrical missing value with other columns that are associated with electrical
test_housing_data.loc[(test_housing_data.electrical.isnull()),
                      ["electrical", "heating", 'central_air', 
                       "heating_qc", "utilities"]]

electrical heating central_air heating_qc utilities
634        NaN    GasA           Y         Gd    AllPub

**Analysis: Index 634 has missing value for electrical**

We will look at similar characteristics that require or associate with electrical such as heating, central_air, heating_qc and utilities to observe the trend.

In [104]:
# To filter the observations that are similar to the characterisitics of Index 634
test_housing_data.loc[(test_housing_data["heating"] == 'GasA') &
                      (test_housing_data["central_air"] == 'Y') &
                      (test_housing_data["heating_qc"] == 'Gd') &
                      (test_housing_data["utilities"] == 'AllPub'),
                      ["electrical", "heating", 'central_air', "heating_qc", "utilities", 'ms_zoning']].head()

electrical heating central_air heating_qc utilities ms_zoning
4       SBrkr    GasA           Y         Gd    AllPub        RL
10      SBrkr    GasA           Y         Gd    AllPub        RL
11      SBrkr    GasA           Y         Gd    AllPub        RM
19      SBrkr    GasA           Y         Gd    AllPub        RM
26      SBrkr    GasA           Y         Gd    AllPub        RL

In [105]:
# To count the values in electrical when it is observed with the similar characteristics
mask = (test_housing_data["heating"] == 'GasA') & (test_housing_data["central_air"] == 'Y') & (test_housing_data["heating_qc"] == 'Gd') & (test_housing_data["utilities"] == 'AllPub')
housing_data.groupby(mask)['electrical'].value_counts()

       electrical
False  SBrkr         669
       FuseA          48
       FuseF          11
       FuseP           5
True   SBrkr         129
       FuseA          13
       FuseF           2
       FuseP           1
Name: electrical, dtype: int64

**Analysis: Using the similar characteristic of the missing values, majority of them have SBrkr as their electrical.**

Majority of the sample have electrical type "SBrkr" for the similar characteristics of Index 634. Thus, we will place 'SBrkr for the electrical column of index 634.

In [106]:
# Change the missing values using the respective values for the respctive columns
test_housing_data.loc[[634],"electrical"] = test_housing_data.loc[[634],"electrical"].fillna('SBrkr')
test_housing_data.loc[[634], ["electrical", "heating", 'central_air', "heating_qc", "utilities", 'ms_zoning']].head()

electrical heating central_air heating_qc utilities ms_zoning
634      SBrkr    GasA           Y         Gd    AllPub        RL

In [107]:
# To check the electrical missing value presence
test_housing_data.loc[(test_housing_data.electrical.isnull()),
                      ["electrical", "heating", 'central_air', 
                       "heating_qc", "utilities"]]

Empty DataFrame
Columns: [electrical, heating, central_air, heating_qc, utilities]
Index: []

**Analysis: The Index 634 missing values has been filled for electrical with relation to other similar characteristics observed from other observations.**

**Summary: test_housing_data for missing values for electrical has been filled.**

**Encode ordinal electrical for housing_data and test_housing_data**

The ordinal electrical will be encoded to numerical form for future analysis.

In [108]:
# Mapping the ordinal electrical for housing_data and test_housing_data for encoding
housing_data["electrical"] = housing_data["electrical"].map({'Mix': 0, 'FuseP': 1, "FuseF": 2, "FuseA": 3, "SBrkr":4})
test_housing_data["electrical"] = test_housing_data["electrical"].map({'Mix': 0, 'FuseP': 1, "FuseF": 2, "FuseA": 3, "SBrkr":4})
print(f"The housing_data electrical unique characters is {(housing_data.electrical.unique())}")
print(f"The test_housing_data electrical unique characters is {(test_housing_data.electrical.unique())}")

The housing_data electrical unique characters is [4 2 3 1 0]
The test_housing_data electrical unique characters is [1 4 3 2]


### 2.3.4.10 Miscellaneous feature missing values

**1. housing_data**

In [109]:
# To check for missing values in miscellaneous feature when miscellaneous value is zero
housing_data.loc[((housing_data["misc_feature"].isnull())), ["misc_feature", "misc_val"]].head()

misc_feature  misc_val
0          NaN         0
1          NaN         0
2          NaN         0
3          NaN         0
4          NaN         0

In [110]:
# To count when miscellaneous value is zero
zero_misc_val = housing_data["misc_val"] == 0
zero_misc_val.value_counts()

True     1986
False      65
Name: misc_val, dtype: int64

**Analysis: The miscellaneous feature has missing value (NaN) when the miscellaneous feature value is zero**

There are a significant amount of missing values for miscellaneous feature (misc_feature) column.
When the miscellaneous feature value is 0, this suggests that there will be no miscellaneous feature and will be indicated as 'None'.

In [111]:
# Change NaN in misc_feature column to 'NA' when misc_val is zero.
modify_with_criteria_onenull_onezero(housing_data, "misc_feature", "misc_val", 'None')
housing_data.loc[((housing_data["misc_feature"].isnull())), ["misc_feature", "misc_val"]]

Empty DataFrame
Columns: [misc_feature, misc_val]
Index: []

**Analysis: Successfully indicated 'None' in miscellaneous feature (misc_feature) column when miscellaneous value is zero.**

There are no missing values left in misc_feature column.

**2. test_housing_data**

In [112]:
# To check for missing values in miscellaneous feature when miscellaneous value is zero
test_housing_data.loc[((test_housing_data["misc_feature"].isnull())), ["misc_feature", "misc_val"]].head()

misc_feature  misc_val
0          NaN         0
1          NaN         0
2          NaN         0
3          NaN         0
4          NaN         0

In [113]:
# To count when miscellaneous value is zero
zero_misc_val = test_housing_data["misc_val"] == 0
zero_misc_val.value_counts()

True     840
False     38
Name: misc_val, dtype: int64

**Analysis: The miscellaneous feature has missing value (NaN) when the miscellaneous feature value is zero**

There are a significant amount of missing values for miscellaneous feature (misc_feature) column.
When the miscellaneous feature value is 0, this suggests that there will be no miscellaneous feature and will be indicated as 'None' for None.

In [114]:
# Change NaN in misc_feature column to 'NA' when misc_val is zero.
modify_with_criteria_onenull_onezero(test_housing_data, "misc_feature", "misc_val", 'None')
test_housing_data.loc[((test_housing_data["misc_feature"].isnull())), ["misc_feature", "misc_val"]]

Empty DataFrame
Columns: [misc_feature, misc_val]
Index: []

**Analysis: Successfully indicated 'None' in miscellaneous feature (misc_feature) column when miscellaneous value is zero.**

There are no missing values left in misc_feature column.

**Summary: Both housing_data and test_housing_data for missing values for miscellaneous features has been filled.**

### 2.3.4.11 Final check for missing values

In [115]:
housing_data.isnull().sum().sort_values(ascending = False)[0:5]

garage_type_Detchd    0
bsmt_exposure         0
exterior_2nd          0
mas_vnr_type          0
mas_vnr_area          0
dtype: int64

In [116]:
test_housing_data.isnull().sum().sort_values(ascending = False)[0:5]

garage_type_Detchd    0
bsmt_exposure         0
exterior_2nd          0
mas_vnr_type          0
mas_vnr_area          0
dtype: int64

### 2.3.4.12 Convert the columns into integer columns

Due to the presence of the missing values, the numerical column is in float while the garage_yr_blt is in object and float. Thus, we will convert it into integer

**1. housing_data**

1.1 Convert the float columns into integer

In [117]:
# List of datatype in the dataframe
housing_data.dtypes.value_counts()

int64      38
object     29
float64    10
uint8       8
dtype: int64

In [118]:
# List of datatype 'float64'
housing_data.select_dtypes(include=['float64']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2051 entries, 0 to 2050
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   lot_frontage    2051 non-null   float64
 1   mas_vnr_area    2051 non-null   float64
 2   bsmtfin_sf_1    2051 non-null   float64
 3   bsmtfin_sf_2    2051 non-null   float64
 4   bsmt_unf_sf     2051 non-null   float64
 5   total_bsmt_sf   2051 non-null   float64
 6   bsmt_full_bath  2051 non-null   float64
 7   bsmt_half_bath  2051 non-null   float64
 8   garage_cars     2051 non-null   float64
 9   garage_area     2051 non-null   float64
dtypes: float64(10)
memory usage: 160.4 KB


In [119]:
#Convert the float columns in housing_data to integer
housing_data[["lot_frontage", "mas_vnr_area", "bsmtfin_sf_1", "bsmtfin_sf_2", "bsmt_unf_sf", "total_bsmt_sf", "bsmt_full_bath", "bsmt_half_bath", "garage_cars", "garage_area"]] = housing_data[["lot_frontage", "mas_vnr_area", "bsmtfin_sf_1", "bsmtfin_sf_2", "bsmt_unf_sf", "total_bsmt_sf", "bsmt_full_bath", "bsmt_half_bath", "garage_cars", "garage_area"]].astype(int)
housing_data.dtypes.value_counts()

int64     38
object    29
int32     10
uint8      8
dtype: int64

In [120]:
print((housing_data[["lot_frontage", "mas_vnr_area", "bsmtfin_sf_1", "bsmtfin_sf_2", "bsmt_unf_sf", "total_bsmt_sf", "bsmt_full_bath", "bsmt_half_bath", "garage_cars", "garage_area"]]).dtypes)

lot_frontage      int32
mas_vnr_area      int32
bsmtfin_sf_1      int32
bsmtfin_sf_2      int32
bsmt_unf_sf       int32
total_bsmt_sf     int32
bsmt_full_bath    int32
bsmt_half_bath    int32
garage_cars       int32
garage_area       int32
dtype: object


**Summary: The numeric columns (float) for housing_data has been converted to integer.**

1.2 Convert the garage_yr_blt into integer

In [121]:
housing_data["garage_yr_blt"].unique()

array([1976.0, 1997.0, 1953.0, 2007.0, 1957.0, 1966.0, 2005.0, 1959.0,
       1952.0, 1969.0, 1971.0, 1900.0, 2000.0, 2004.0, 1916.0, 1963.0,
       1977.0, 2009.0, 1968.0, 1992.0, 1955.0, 1961.0, 1973.0, 1937.0,
       'None', 2003.0, 1981.0, 1931.0, 1995.0, 1958.0, 1965.0, 2006.0,
       1978.0, 1954.0, 1935.0, 1951.0, 1996.0, 1999.0, 1920.0, 1930.0,
       1924.0, 1960.0, 1949.0, 1986.0, 1956.0, 1994.0, 1979.0, 1964.0,
       2001.0, 1972.0, 1939.0, 1962.0, 1927.0, 1948.0, 1967.0, 1993.0,
       2010.0, 1915.0, 1987.0, 1970.0, 1988.0, 1982.0, 1941.0, 1984.0,
       1942.0, 1950.0, 2002.0, 1975.0, 2008.0, 1974.0, 1998.0, 1918.0,
       1938.0, 1985.0, 1923.0, 1980.0, 1991.0, 1946.0, 1940.0, 1990.0,
       1896.0, 1983.0, 1914.0, 1945.0, 1921.0, 1925.0, 1926.0, 1936.0,
       1932.0, 1947.0, 1929.0, 1910.0, 1917.0, 1922.0, 1934.0, 1989.0,
       1928.0, 2207.0, 1933.0, 1895.0, 1919.0], dtype=object)

In [122]:
# Converting the missing values in garage_yr_blt to 'NA' and the rest convert to integer
housing_data["garage_yr_blt"] = housing_data["garage_yr_blt"].apply(lambda x:'None' if x == 'None' else int(x))

In [123]:
housing_data["garage_yr_blt"].unique()

array([1976, 1997, 1953, 2007, 1957, 1966, 2005, 1959, 1952, 1969, 1971,
       1900, 2000, 2004, 1916, 1963, 1977, 2009, 1968, 1992, 1955, 1961,
       1973, 1937, 'None', 2003, 1981, 1931, 1995, 1958, 1965, 2006, 1978,
       1954, 1935, 1951, 1996, 1999, 1920, 1930, 1924, 1960, 1949, 1986,
       1956, 1994, 1979, 1964, 2001, 1972, 1939, 1962, 1927, 1948, 1967,
       1993, 2010, 1915, 1987, 1970, 1988, 1982, 1941, 1984, 1942, 1950,
       2002, 1975, 2008, 1974, 1998, 1918, 1938, 1985, 1923, 1980, 1991,
       1946, 1940, 1990, 1896, 1983, 1914, 1945, 1921, 1925, 1926, 1936,
       1932, 1947, 1929, 1910, 1917, 1922, 1934, 1989, 1928, 2207, 1933,
       1895, 1919], dtype=object)

**Summary: The garage_yr_blt values (float) for housing_data has been converted to integer.**

**2. test_housing_data**

1.1 Convert the float columns into integer

In [124]:
# List of datatype in the dataframe
test_housing_data.dtypes.value_counts()

int64      45
object     29
uint8       8
float64     2
dtype: int64

In [125]:
# List of datatype 'float64'
test_housing_data.select_dtypes(include=['float64']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 878 entries, 0 to 877
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   lot_frontage  878 non-null    float64
 1   mas_vnr_area  878 non-null    float64
dtypes: float64(2)
memory usage: 13.8 KB


In [126]:
#Convert the float columns in housing_data to integer
test_housing_data[["lot_frontage", "mas_vnr_area"]] = test_housing_data[["lot_frontage", "mas_vnr_area"]].astype(int)
test_housing_data.dtypes.value_counts()

int64     45
object    29
uint8      8
int32      2
dtype: int64

In [127]:
print((test_housing_data[["lot_frontage", "mas_vnr_area"]]).dtypes)

lot_frontage    int32
mas_vnr_area    int32
dtype: object


**Summary: The numeric columns (float) for test_housing_data has been converted to integer.**

1.2 Convert the garage_yr_blt into integer

In [128]:
test_housing_data["garage_yr_blt"].unique()

array([1910.0, 1977.0, 2006.0, 1935.0, 1963.0, 1972.0, 1959.0, 1978.0,
       2004.0, 1980.0, 1991.0, 1993.0, 1954.0, 2000.0, 1943.0, 1957.0,
       1940.0, 1956.0, 1961.0, 1925.0, 1968.0, 1982.0, 1969.0, 2007.0,
       1989.0, 1920.0, 1937.0, 'None', 1979.0, 1962.0, 1950.0, 1973.0,
       2001.0, 1952.0, 1953.0, 1999.0, 2009.0, 1998.0, 1974.0, 1951.0,
       1987.0, 2003.0, 1924.0, 1970.0, 1975.0, 1958.0, 1971.0, 1992.0,
       1994.0, 2005.0, 1960.0, 1967.0, 2002.0, 1997.0, 1981.0, 1938.0,
       1988.0, 1939.0, 1927.0, 1984.0, 1964.0, 1995.0, 2008.0, 1966.0,
       1941.0, 1983.0, 1906.0, 1930.0, 1955.0, 1946.0, 1996.0, 1928.0,
       1976.0, 1915.0, 1923.0, 1965.0, 1947.0, 1900.0, 1918.0, 1934.0,
       1932.0, 1986.0, 2010.0, 1985.0, 1949.0, 1948.0, 1917.0, 1990.0,
       1921.0, 1926.0, 1931.0, 1916.0, 1922.0, 1908.0], dtype=object)

In [129]:
# Converting the missing values in garage_yr_blt to 'NA' and the rest convert to integer
test_housing_data["garage_yr_blt"] = test_housing_data["garage_yr_blt"].apply(lambda x:'None' if x == 'None' else int(x))

In [130]:
test_housing_data["garage_yr_blt"].unique()

array([1910, 1977, 2006, 1935, 1963, 1972, 1959, 1978, 2004, 1980, 1991,
       1993, 1954, 2000, 1943, 1957, 1940, 1956, 1961, 1925, 1968, 1982,
       1969, 2007, 1989, 1920, 1937, 'None', 1979, 1962, 1950, 1973, 2001,
       1952, 1953, 1999, 2009, 1998, 1974, 1951, 1987, 2003, 1924, 1970,
       1975, 1958, 1971, 1992, 1994, 2005, 1960, 1967, 2002, 1997, 1981,
       1938, 1988, 1939, 1927, 1984, 1964, 1995, 2008, 1966, 1941, 1983,
       1906, 1930, 1955, 1946, 1996, 1928, 1976, 1915, 1923, 1965, 1947,
       1900, 1918, 1934, 1932, 1986, 2010, 1985, 1949, 1948, 1917, 1990,
       1921, 1926, 1931, 1916, 1922, 1908], dtype=object)

**Summary: The garage_yr_blt values (float) for test_housing_data has been converted to integer.**

### 2.3.4.13 Encode the ordinal columns for future analysis

For the ease of future analysis, the ordinal columns will be ordinally encoded.

**1. housing_data**

In [131]:
# Encode the remaining ordinal columns with reference to data dictionary
housing_data["lot_shape"] = housing_data["lot_shape"].map({'IR3': 0, 'IR2': 1, 'IR1': 2, "Reg": 3})
housing_data["utilities"] = housing_data["utilities"].map({'ELO': 0, 'NoSeWa': 1, 'NoSewr': 2, "AllPub": 3})
housing_data["land_slope"] = housing_data["land_slope"].map({'Sev': 0, 'Mod': 1, 'Gtl': 2})
housing_data["exter_qual"] = housing_data["exter_qual"].map({'Po': 0, 'Fa': 1, "TA": 2, "Gd": 3, "Ex":4})
housing_data["exter_cond"] = housing_data["exter_cond"].map({'Po': 0, 'Fa': 1, "TA": 2, "Gd": 3, "Ex":4})
housing_data["heating_qc"] = housing_data["heating_qc"].map({'Po': 0, 'Fa': 1, "TA": 2, "Gd": 3, "Ex":4})
housing_data["kitchen_qual"] = housing_data["kitchen_qual"].map({'Po': 0, 'Fa': 1, "TA": 2, "Gd": 3, "Ex":4})
housing_data["functional"] = housing_data["functional"].map({'Sal': 0, 'Sev': 1, "Maj2": 2, "Maj1": 3, "Mod":4, "Min2": 5, "Min1": 6, "Typ": 7})
housing_data["paved_drive"] = housing_data["paved_drive"].map({'N': 0, 'P': 1, "Y": 2})
print(f"The lot_shape unique characters is {(housing_data.lot_shape.unique())}")
print(f"The utilities unique characters is {(housing_data.utilities.unique())}")
print(f"The land_slope unique characters is {(housing_data.land_slope.unique())}")
print(f"The exter_qual unique characters is {(housing_data.exter_qual.unique())}")
print(f"The exter_cond unique characters is {(housing_data.exter_cond.unique())}")
print(f"The heating_qc unique characters is {(housing_data.heating_qc.unique())}")
print(f"The kitchen_qual unique characters is {(housing_data.kitchen_qual.unique())}")
print(f"The functional unique characters is {(housing_data.functional.unique())}")
print(f"The paved_drive unique characters is {(housing_data.paved_drive.unique())}")

The lot_shape unique characters is [2 3 1 0]
The utilities unique characters is [3 1 2]
The land_slope unique characters is [2 0 1]
The exter_qual unique characters is [3 2 4 1]
The exter_cond unique characters is [2 3 1 4 0]
The heating_qc unique characters is [4 2 3 1 0]
The kitchen_qual unique characters is [3 2 1 4]
The functional unique characters is [7 4 5 3 6 1 0 2]
The paved_drive unique characters is [2 0 1]


**2. test_housing_data**

In [132]:
# Encode the remaining ordinal columns with reference to data dictionary
test_housing_data["lot_shape"] = test_housing_data["lot_shape"].map({'IR3': 0, 'IR2': 1, 'IR1': 2, "Reg": 3})
test_housing_data["utilities"] = test_housing_data["utilities"].map({'ELO': 0, 'NoSeWa': 1, 'NoSewr': 2, "AllPub": 3})
test_housing_data["land_slope"] = test_housing_data["land_slope"].map({'Sev': 0, 'Mod': 1, 'Gtl': 2})
test_housing_data["exter_qual"] = test_housing_data["exter_qual"].map({'Po': 0, 'Fa': 1, "TA": 2, "Gd": 3, "Ex":4})
test_housing_data["exter_cond"] = test_housing_data["exter_cond"].map({'Po': 0, 'Fa': 1, "TA": 2, "Gd": 3, "Ex":4})
test_housing_data["heating_qc"] = test_housing_data["heating_qc"].map({'Po': 0, 'Fa': 1, "TA": 2, "Gd": 3, "Ex":4})
test_housing_data["kitchen_qual"] = test_housing_data["kitchen_qual"].map({'Po': 0, 'Fa': 1, "TA": 2, "Gd": 3, "Ex":4})
test_housing_data["functional"] = test_housing_data["functional"].map({'Sal': 0, 'Sev': 1, "Maj2": 2, "Maj1": 3, "Mod":4, "Min2": 5, "Min1": 6, "Typ": 7})
test_housing_data["paved_drive"] = test_housing_data["paved_drive"].map({'N': 0, 'P': 1, "Y": 2})
print(f"The lot_shape unique characters is {(test_housing_data.lot_shape.unique())}")
print(f"The utilities unique characters is {(test_housing_data.utilities.unique())}")
print(f"The land_slope unique characters is {(test_housing_data.land_slope.unique())}")
print(f"The exter_qual unique characters is {(test_housing_data.exter_qual.unique())}")
print(f"The exter_cond unique characters is {(test_housing_data.exter_cond.unique())}")
print(f"The heating_qc unique characters is {(test_housing_data.heating_qc.unique())}")
print(f"The kitchen_qual unique characters is {(test_housing_data.kitchen_qual.unique())}")
print(f"The functional unique characters is {(test_housing_data.functional.unique())}")
print(f"The paved_drive unique characters is {(test_housing_data.paved_drive.unique())}")

The lot_shape unique characters is [3 2 0 1]
The utilities unique characters is [3 2]
The land_slope unique characters is [2 1 0]
The exter_qual unique characters is [2 3 1 4]
The exter_cond unique characters is [1 2 3 4 0]
The heating_qc unique characters is [3 2 4 1]
The kitchen_qual unique characters is [1 2 3 4 0]
The functional unique characters is [7 5 6 4 3 2]
The paved_drive unique characters is [2 0 1]


**Summary: Both housing_data and test_housing_data ordinal columns has been converted to integer.**

## 3. Summary

For both housing_data and test_housing_data:

* Rename the column for coherent and easier navigation and drop the columns of 'id' and 'pid'.
* Rename the values of ms_zoning column to remove '(all)' and '(agr)'.
* Fill the missing values for column having missing values in the alley, basement, fence, fireplace, frontage, garage, masonry, pool and miscellaneous features columns based on the similar characteristics of the missing values.
* The missing values that are ordinal and nominal category has been converted to integer
* The numeric columns (float) has been converted to integer
* The ordinal columns have been convereted to integer

For test_housing_data:
* The additional column of missing values in elecrical has been filled.

## 4. Exporting Data

In [133]:
# Placed the # to refrain from executing
#housing_data.to_csv("../code/housing_data_clean_id.csv", index = False) 
#test_housing_data.to_csv("../code/test_housing_data_clean_id.csv", index = False) 

## 5. References

[1] "Public and Private Lnads Percentages," 1991.[Online]. Available: https://www.summitpost.org/public-and-private-land-percentages-by-us-states/186111. [Accessed: Apr. 9. 2021].

[2] "Ames," *Niche.com.Inc*, 2021. [Online]. Available: https://www.niche.com/places-to-live/ames-story-ia/. [Accessed: Apr. 9. 2021]

[3] "QuickFacts Ames City, Iowa," *United States Census Bureau*, 2019. [Online]. Available: https://www.census.gov/quickfacts/amescityiowa. [Accessed: Apr. 6. 2021].

[4] "Housing in Ames, Iowa," *Sperling's Best Places*, [Online]. Available: https://www.bestplaces.net/housing/city/iowa/ames [Accessed: Apr. 9. 2021]

[5] "Iowa's affordable housing struggle," *The Gazette*, 2018.[Online]. Available: https://www.thegazette.com/regional-development/iowas-affordable-housing-struggle/. [Accessed: Apr. 9. 2021].